<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="2.1 End-of-Chapter Exercises | Solutions for ‘Introdcution To The New Statistics’" />
<meta property="og:type" content="book" />


<meta property="og:description" content="This website is an interactive companion book for Introduction to the New Statistics (abbreviated itns). It offers interactive quizzes with solutions, interactive questions and answers for the in-chapter-exercises and an R tutorial for the end-of-chapter exercises." />


<meta name="author" content="Peter Baumgartner" />

<meta name="date" content="2020-02-02" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="This website is an interactive companion book for Introduction to the New Statistics (abbreviated itns). It offers interactive quizzes with solutions, interactive questions and answers for the in-chapter-exercises and an R tutorial for the end-of-chapter exercises.">

<title>2.1 End-of-Chapter Exercises | Solutions for ‘Introdcution To The New Statistics’</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/darkly.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #2a211c;
    color: #bdae9d;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #bdae9d;  padding-left: 4px; }
div.sourceCode
  { color: #bdae9d; background-color: #2a211c; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ffff00; } /* Alert */
code span.an { color: #0066ff; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { } /* Attribute */
code span.bn { color: #44aa43; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #43a8ed; font-weight: bold; } /* ControlFlow */
code span.ch { color: #049b0a; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #0066ff; font-weight: bold; font-style: italic; } /* Comment */
code span.do { color: #0066ff; font-style: italic; } /* Documentation */
code span.dt { text-decoration: underline; } /* DataType */
code span.dv { color: #44aa43; } /* DecVal */
code span.er { color: #ffff00; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #44aa43; } /* Float */
code span.fu { color: #ff9358; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #0066ff; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #43a8ed; font-weight: bold; } /* Keyword */
code span.op { } /* Operator */
code span.pp { font-weight: bold; } /* Preprocessor */
code span.sc { color: #049b0a; } /* SpecialChar */
code span.ss { color: #049b0a; } /* SpecialString */
code span.st { color: #049b0a; } /* String */
code span.va { } /* Variable */
code span.vs { color: #049b0a; } /* VerbatimString */
code span.wa { color: #ffff00; font-weight: bold; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<link rel="stylesheet" href="css/mystyle.css" type="text/css" />

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li class="has-sub"><a href="index.html#introduction">Introduction</a><ul>
<li><a href="three-types-of-content.html#three-types-of-content">Three Types of Content</a></li>
<li class="has-sub"><a href="general-setup.html#general-setup">General Setup</a><ul>
<li><a href="general-setup.html#global-options">Global Options</a></li>
<li><a href="general-setup.html#installing-and-loading-r-packages">Installing and loading R packages</a></li>
<li><a href="general-setup.html#theme-adaption-for-the-graphic-display-with-ggplot2">Theme adaption for the graphic display with <code>ggplot2</code></a></li>
</ul></li>
</ul></li>
<li><a href="1-research-questions.html#research-questions"><span class="toc-section-number">1</span> Research Questions</a></li>
<li class="has-sub"><a href="2-picturing-describing-data.html#picturing-describing-data"><span class="toc-section-number">2</span> Picturing &amp; Describing Data</a><ul>
<li class="has-sub"><a href="2-1-end-of-chapter-exercises.html#end-of-chapter-exercises"><span class="toc-section-number">2.1</span> End-of-Chapter Exercises</a><ul>
<li class="has-sub"><a href="2-1-end-of-chapter-exercises.html#calculating-decriptive-statistics"><span class="toc-section-number">2.1.1</span> Calculating decriptive statistics</a><ul>
<li><a href="2-1-end-of-chapter-exercises.html#description"><span class="toc-section-number">2.1.1.1</span> Description</a></li>
<li><a href="2-1-end-of-chapter-exercises.html#solution"><span class="toc-section-number">2.1.1.2</span> Solution</a></li>
</ul></li>
<li class="has-sub"><a href="2-1-end-of-chapter-exercises.html#loading-our-first-data-set"><span class="toc-section-number">2.1.2</span> Loading our first data set</a><ul>
<li><a href="2-1-end-of-chapter-exercises.html#inspecting-the-itns-package"><span class="toc-section-number">2.1.2.1</span> Inspecting the <code>itns</code>-package</a></li>
<li><a href="2-1-end-of-chapter-exercises.html#reading-the-codebook-for-college-survey1"><span class="toc-section-number">2.1.2.2</span> Reading the codebook for <code>college-survey1</code></a></li>
</ul></li>
<li class="has-sub"><a href="2-1-end-of-chapter-exercises.html#distribution-of-positive-affect-scores"><span class="toc-section-number">2.1.3</span> Distribution of positive affect scores</a><ul>
<li><a href="2-1-end-of-chapter-exercises.html#visualize-the-distribution"><span class="toc-section-number">2.1.3.1</span> Visualize the distribution</a></li>
<li class="has-sub"><a href="2-1-end-of-chapter-exercises.html#histogram"><span class="toc-section-number">2.1.3.2</span> Histogram</a><ul>
<li><a href="2-1-end-of-chapter-exercises.html#addressing-the-notification"><span class="toc-section-number">2.1.3.2.1</span> Addressing the notification</a></li>
<li><a href="2-1-end-of-chapter-exercises.html#addressing-the-warning"><span class="toc-section-number">2.1.3.2.2</span> Addressing the warning</a></li>
</ul></li>
<li><a href="2-1-end-of-chapter-exercises.html#dot-plot"><span class="toc-section-number">2.1.3.3</span> Dot plot</a></li>
<li><a href="2-1-end-of-chapter-exercises.html#interpretation"><span class="toc-section-number">2.1.3.4</span> Interpretation</a></li>
</ul></li>
<li><a href="2-1-end-of-chapter-exercises.html#distribution-of-student-age"><span class="toc-section-number">2.1.4</span> Distribution of student age</a></li>
<li><a href="2-1-end-of-chapter-exercises.html#distribution-of-exercise-scores"><span class="toc-section-number">2.1.5</span> Distribution of exercise scores</a></li>
<li><a href="2-1-end-of-chapter-exercises.html#distribution-of-raven-scores-and-gpa"><span class="toc-section-number">2.1.6</span> Distribution of Raven scores and GPA</a></li>
<li><a href="2-1-end-of-chapter-exercises.html#presentation-of-the-gender-distribution"><span class="toc-section-number">2.1.7</span> Presentation of the gender distribution</a></li>
</ul></li>
<li class="has-sub"><a href="2-2-put-some-indidual-scores-in-context.html#put-some-indidual-scores-in-context"><span class="toc-section-number">2.2</span> Put some indidual scores in context</a><ul>
<li><a href="2-2-put-some-indidual-scores-in-context.html#female-student-on-the-ravens-measure"><span class="toc-section-number">2.2.1</span> Female student on the Ravens measure</a></li>
<li><a href="2-2-put-some-indidual-scores-in-context.html#the-same-student-in-gpa"><span class="toc-section-number">2.2.2</span> The same student in GPA</a></li>
</ul></li>
<li class="has-sub"><a href="2-3-comparing-the-positive-and-negative-affect-of-a-partipant.html#comparing-the-positive-and-negative-affect-of-a-partipant"><span class="toc-section-number">2.3</span> Comparing the positive and negative affect of a partipant</a><ul>
<li><a href="2-3-comparing-the-positive-and-negative-affect-of-a-partipant.html#positve-affect"><span class="toc-section-number">2.3.0.1</span> Positve Affect</a></li>
<li><a href="2-3-comparing-the-positive-and-negative-affect-of-a-partipant.html#negative-affect"><span class="toc-section-number">2.3.0.2</span> Negative Affect</a></li>
<li><a href="2-3-comparing-the-positive-and-negative-affect-of-a-partipant.html#comparison-positive-with-negative-affect"><span class="toc-section-number">2.3.0.3</span> Comparison: Positive with Negative Affect</a></li>
<li><a href="2-3-comparing-the-positive-and-negative-affect-of-a-partipant.html#determine-outliers"><span class="toc-section-number">2.3.1</span> Determine outliers</a></li>
</ul></li>
<li class="has-sub"><a href="2-4-religious-beliefs.html#religious-beliefs"><span class="toc-section-number">2.4</span> Religious Beliefs</a><ul>
<li><a href="2-4-religious-beliefs.html#estimate-the-distribution"><span class="toc-section-number">2.4.1</span> Estimate the distribution</a></li>
<li><a href="2-4-religious-beliefs.html#graphic-of-the-religious-data"><span class="toc-section-number">2.4.2</span> Graphic of the religious data</a></li>
<li><a href="2-4-religious-beliefs.html#evaluate-the-different-location-parameters"><span class="toc-section-number">2.4.3</span> Evaluate the different location parameters</a></li>
</ul></li>
<li class="has-sub"><a href="2-5-working-with-the-oiginal-excel-data-set.html#working-with-the-oiginal-excel-data-set"><span class="toc-section-number">2.5</span> Working with the oiginal Excel data set</a><ul>
<li><a href="2-5-working-with-the-oiginal-excel-data-set.html#load-data-set-from-excel-file"><span class="toc-section-number">2.5.1</span> Load data set from Excel file</a></li>
<li><a href="2-5-working-with-the-oiginal-excel-data-set.html#problems-with-the-exercise-variable"><span class="toc-section-number">2.5.2</span> Problems with the Exercise variable</a></li>
<li><a href="2-5-working-with-the-oiginal-excel-data-set.html#problems-with-the-ravens_score"><span class="toc-section-number">2.5.3</span> Problems with the Ravens_Score</a></li>
<li><a href="2-5-working-with-the-oiginal-excel-data-set.html#gender-data"><span class="toc-section-number">2.5.4</span> Gender data</a></li>
</ul></li>
</ul></li>
<li><a href="references.html#references">References</a></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="end-of-chapter-exercises" class="section level2">
<h2><span class="header-section-number">2.1</span> End-of-Chapter Exercises</h2>
<div id="calculating-decriptive-statistics" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Calculating decriptive statistics</h3>
<div id="description" class="section level4">
<h4><span class="header-section-number">2.1.1.1</span> Description</h4>
<p>The following table contains a set of ACT scores from a sample of college students. The ACT is a standardized college-readiness exam taken by many U.S. students; scores can range fro 1 to 36.</p>
<table>
<thead>
<tr class="header">
<th>Student</th>
<th>ACT</th>
<th><span class="math inline">\((X~i~ - M)\)</span></th>
<th><span class="math inline">\((X~i~ - M)^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>26</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>2</td>
<td>24</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>3</td>
<td>28</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>4</td>
<td>31</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>5</td>
<td>20</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td>27</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td>18</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>8</td>
<td>17</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>9</td>
<td>21</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>10</td>
<td>29</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>11</td>
<td>24</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Total</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha">
<li><strong>Location:</strong> Calculate the mean (<em>M</em>), median, and mode for this sample.</li>
<li><strong>Spread:</strong> Calculate the standard deviation (<em>s</em>), range and interquartile range for this sample. For <em>s</em>, fill in the two columns on the right in the table above, then use the formula to calculate <em>s</em> yourself.</li>
</ol>
</div>
<div id="solution" class="section level4">
<h4><span class="header-section-number">2.1.1.2</span> Solution</h4>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="2-1-end-of-chapter-exercises.html#cb21-1"></a><span class="op">&gt;</span><span class="st"> </span>ACT &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">26</span>, <span class="dv">24</span>, <span class="dv">28</span>, <span class="dv">31</span>, <span class="dv">20</span>, <span class="dv">27</span>, <span class="dv">18</span>, <span class="dv">17</span>, <span class="dv">21</span>, <span class="dv">29</span>, <span class="dv">24</span>)</span></code></pre></div>
<p>With <code>summary</code> there is a covenient command in R to print out some of the most important descriptive statistics.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="2-1-end-of-chapter-exercises.html#cb22-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(ACT)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   17.00   20.50   24.00   24.09   27.50   31.00</code></pre>
<p>The summary command does not display mode, variance, standard deviation and IQR. With the exception of mode all these command are included in the base R installation. To calculate the mode we need <em>modeest</em>, a package for mode estimation.</p>
<p>In R there are for the same task often several solution possible. I will add some of them.</p>
<table>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Command in R</th>
<th align="right">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean <em>M</em></td>
<td><code>round(mean(ACT),2)</code></td>
<td align="right">24.09</td>
</tr>
<tr class="even">
<td>Median (V1)</td>
<td><code>median(ACT)</code></td>
<td align="right">24</td>
</tr>
<tr class="odd">
<td>Median (V2)</td>
<td><code>fivenum(ACT)[3]</code></td>
<td align="right">24</td>
</tr>
<tr class="even">
<td>quantile (V3)</td>
<td><code>quantile(ACT)[[3]]</code></td>
<td align="right">24</td>
</tr>
<tr class="odd">
<td>Mode</td>
<td><code>mfv(ACT)</code></td>
<td align="right">24</td>
</tr>
<tr class="even">
<td>Variance</td>
<td><code>round(var(ACT),2)</code></td>
<td align="right">21.29</td>
</tr>
<tr class="odd">
<td><em>s</em></td>
<td><code>round(sd(ACT),2)</code></td>
<td align="right">4.61</td>
</tr>
<tr class="even">
<td>Range (V1)</td>
<td><code>range(ACT)</code></td>
<td align="right">17, 31</td>
</tr>
<tr class="odd">
<td>Range (V2)</td>
<td><code>fivenum(ACT)[c(1,5)]</code></td>
<td align="right">17, 31</td>
</tr>
<tr class="even">
<td>IQR</td>
<td><code>IQR(ACT)</code></td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td>Q1,Q3</td>
<td><code>fivenum(ACT)[c(2,4)]</code></td>
<td align="right">20.5, 27.5</td>
</tr>
</tbody>
</table>
<p>To populate the table programmatically I will convert ACT to a data frame <code>ACT_df = as.data.frame(ACT)</code> resp. in a <code>tibble</code> as <a href="https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html">tibbles has some advantages over data frames</a>. (The <code>tibble</code> package is part of the <code>tidyverse</code>.)</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="2-1-end-of-chapter-exercises.html#cb24-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="co">### Calling `as_tibble()` on a vector is discouraged, because the behavior is likely to change in the future.  I</span></span>
<span id="cb24-2"><a href="2-1-end-of-chapter-exercises.html#cb24-2"></a><span class="er">&gt;</span><span class="st"> </span><span class="co">### am using instead the `enframe` command</span></span>
<span id="cb24-3"><a href="2-1-end-of-chapter-exercises.html#cb24-3"></a><span class="er">&gt;</span><span class="st"> </span>ACT_df &lt;-<span class="st"> </span><span class="kw">enframe</span>(ACT, <span class="dt">name =</span> <span class="st">&quot;Student&quot;</span>, <span class="dt">value =</span> <span class="st">&quot;ACT&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="2-1-end-of-chapter-exercises.html#cb25-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="co">## using the pipe operator (https://magrittr.tidyverse.org/) using mutate from the dplyr package which is also</span></span>
<span id="cb25-2"><a href="2-1-end-of-chapter-exercises.html#cb25-2"></a><span class="er">&gt;</span><span class="st"> </span><span class="co">## included in tidyverse</span></span>
<span id="cb25-3"><a href="2-1-end-of-chapter-exercises.html#cb25-3"></a><span class="er">&gt;</span><span class="st"> </span>ACT_df &lt;-<span class="st"> </span>ACT_df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="st">`</span><span class="dt">Xi-M</span><span class="st">`</span> =<span class="st"> </span><span class="kw">round</span>(ACT_df<span class="op">$</span>ACT <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(ACT_df<span class="op">$</span>ACT), <span class="dv">2</span>), <span class="st">`</span><span class="dt">(Xi-M)^2</span><span class="st">`</span> =<span class="st"> </span><span class="kw">round</span>(<span class="st">`</span><span class="dt">Xi-M</span><span class="st">`</span><span class="op">^</span><span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb25-4"><a href="2-1-end-of-chapter-exercises.html#cb25-4"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb25-5"><a href="2-1-end-of-chapter-exercises.html#cb25-5"></a><span class="er">&gt;</span><span class="st"> </span></span>
<span id="cb25-6"><a href="2-1-end-of-chapter-exercises.html#cb25-6"></a><span class="er">&gt;</span><span class="st"> </span>ACT_df &lt;-<span class="st"> </span>ACT_df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">adorn_totals</span>(<span class="st">&quot;row&quot;</span>)  <span class="co"># janitor package to add totals</span></span>
<span id="cb25-7"><a href="2-1-end-of-chapter-exercises.html#cb25-7"></a><span class="op">&gt;</span><span class="st"> </span>ACT_df[<span class="dv">12</span>, <span class="dv">3</span>] &lt;-<span class="st"> &quot;   &quot;</span>  <span class="co"># summing up Xi-M does not make sense</span></span>
<span id="cb25-8"><a href="2-1-end-of-chapter-exercises.html#cb25-8"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb25-9"><a href="2-1-end-of-chapter-exercises.html#cb25-9"></a><span class="er">&gt;</span><span class="st"> </span></span>
<span id="cb25-10"><a href="2-1-end-of-chapter-exercises.html#cb25-10"></a><span class="er">&gt;</span><span class="st"> </span>knitr<span class="op">::</span><span class="kw">kable</span>(ACT_df, <span class="dt">booktabs =</span> <span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&quot;ACT Scores for Exercise 1 of Chapter 3&quot;</span>, <span class="dt">align =</span> <span class="st">&quot;rrrr&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:generate-columns-with-package-dplyr">Table 1.1: </span>ACT Scores for Exercise 1 of Chapter 3</caption>
<thead>
<tr class="header">
<th align="right">Student</th>
<th align="right">ACT</th>
<th align="right">Xi-M</th>
<th align="right">(Xi-M)^2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">26</td>
<td align="right">1.91</td>
<td align="right">3.65</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">24</td>
<td align="right">-0.09</td>
<td align="right">0.01</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">28</td>
<td align="right">3.91</td>
<td align="right">15.29</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">31</td>
<td align="right">6.91</td>
<td align="right">47.75</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">20</td>
<td align="right">-4.09</td>
<td align="right">16.73</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">27</td>
<td align="right">2.91</td>
<td align="right">8.47</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">18</td>
<td align="right">-6.09</td>
<td align="right">37.09</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">17</td>
<td align="right">-7.09</td>
<td align="right">50.27</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">21</td>
<td align="right">-3.09</td>
<td align="right">9.55</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">29</td>
<td align="right">4.91</td>
<td align="right">24.11</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="right">24</td>
<td align="right">-0.09</td>
<td align="right">0.01</td>
</tr>
<tr class="even">
<td align="right">Total</td>
<td align="right">265</td>
<td align="right"></td>
<td align="right">212.93</td>
</tr>
</tbody>
</table>
<p>This table has not the same information as in the book p.505. At first I tried to build it similar but this complicates everything as it is not suitable for using R.</p>
</div>
</div>
<div id="loading-our-first-data-set" class="section level3">
<h3><span class="header-section-number">2.1.2</span> Loading our first data set</h3>
<div id="inspecting-the-itns-package" class="section level4">
<h4><span class="header-section-number">2.1.2.1</span> Inspecting the <code>itns</code>-package</h4>
<p>In the task description of the <em>itns</em>-book you will find the following passage (p.68):</p>
<blockquote>
<p>From the book website, load the <code>College_Survey_1</code> data set. This is a large data set containing data from a wide-ranging survey of college students. You can read the code book for the data file to get a better sense of the different variables measured.</p>
</blockquote>
<p>But you do not need to load the file into R as there are all these data sets already included in the <code>itns</code> package, which we already have loaded into R. In this package the data sets are already cleaned and made compatibel with the R language. This is a great advantage and helps us to concentrate just on the exercises. As in real life you will not have your data already cleaned, I will in the last section of this chapter explain some of the necessary procedures you whould normally apply to every new data set you want to work with.</p>
<p>In the documentation the name of the <code>College_Survey_1</code> data set in the <code>itns</code> pacakge is <code>college_survey1</code>. When you have already the package attached you can find this out with the command <code>ls("package:itns")</code> our better in RStudio with the console command <code>help(package = itns)</code>. (Our you can also go to the “Packages” tab and search for “itns”) The former displays the objects of the package in your RMarkdown file, the latter opens up the documentation page in the RStudio help tab.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="2-1-end-of-chapter-exercises.html#cb26-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ls</span>(<span class="st">&quot;package:itns&quot;</span>)  <span class="co"># list all objects of the itns package</span></span></code></pre></div>
<pre><code>##  [1] &quot;altruism_happiness&quot;   &quot;anchor_estimate&quot;      &quot;anchor_estimate_ma&quot;   &quot;body_well&quot;           
##  [5] &quot;campus_involvement&quot;   &quot;clean_moral_johnson&quot;  &quot;clean_moral_schall&quot;   &quot;cohensd_rm&quot;          
##  [9] &quot;college_survey1&quot;      &quot;college_survey2&quot;      &quot;dana&quot;                 &quot;emotion_heartrate&quot;   
## [13] &quot;exam_scores&quot;          &quot;flag_priming_ma&quot;      &quot;home_prices&quot;          &quot;home_prices_holdout&quot; 
## [17] &quot;labels_flavor&quot;        &quot;math_gender_iat&quot;      &quot;math_gender_iat_ma&quot;   &quot;natsal&quot;              
## [21] &quot;organic_moral&quot;        &quot;pen_laptop1&quot;          &quot;pen_laptop2&quot;          &quot;power_performance_ma&quot;
## [25] &quot;rattan&quot;               &quot;religion_sharing&quot;     &quot;religious_belief&quot;     &quot;self_explain_time&quot;   
## [29] &quot;sleep_beauty&quot;         &quot;stickgold&quot;            &quot;study_strategies&quot;     &quot;thomason1&quot;           
## [33] &quot;thomason2&quot;            &quot;thomason3&quot;            &quot;videogame_aggression&quot;</code></pre>
<p>Further on I will only describe the RStudio version. RStudio is the most productive R IDE (Integrated Development Environment) I know about. It is free and works with many platforms. You can download the lastest version at <a href="https://www.rstudio.com/products/rstudio/download/#download" class="uri">https://www.rstudio.com/products/rstudio/download/#download</a></p>
<p>To detect the name of the variables (= columns) and the data structure we use the RStudio <code>View</code> command:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="2-1-end-of-chapter-exercises.html#cb28-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">View</span>(college_survey1)  <span class="co"># opens the data set in the RStudio data browser</span></span></code></pre></div>
</div>
<div id="reading-the-codebook-for-college-survey1" class="section level4">
<h4><span class="header-section-number">2.1.2.2</span> Reading the codebook for <code>college-survey1</code></h4>
<p>Even the data set is already included in the <code>itns</code> package, you still will need to go to the companion website and download the data set as you will need the code book to understand what all the variables and codes mean. To save you time I have it included here.</p>
<p>But keep in mind that the variable names in the <code>college-survey1</code> are slighty different than in <code>College_Survey_1</code>. The main difference is that the R variables are not capitalized. As R is case sensitive, we need always to look up the correct names for the R variables (columns).</p>
<p><strong>Survey of College Attitudes</strong></p>
<p>This is data from survey of college students. The survey was put together as a classroom project, and measures a number of different constructs. Note that not all participants elected to answer all items–blanks represent scales that were not completed by that participant.</p>
<ul>
<li>ID -</li>
<li>Gender : Self-reported gender, Male or Female</li>
<li>Gender_Code: 1 for Female, 2 for Male</li>
<li>Age: Self-reported age in years</li>
<li>School_Year - Self reported, First-year, sophomore, junior, senior, or post-bac</li>
<li>School_Year_Code: 1 = first-year, 2 = sophomore,3 = junior, 4 = senior, 5 = post-bac</li>
<li>Transfer: No if student did not transfer to current school, Yes if student transferred to current school</li>
<li>Transfer_Code: 0 = not a transfer student, 1 = transfer student</li>
<li>Student_Athlete: self-reported, non-athlete, or athlete in or out of season</li>
<li>Student_Athlete_Code: 0 = not a student athlete, 1 = student athlete</li>
<li>Wealth_SR: Single item: “Considering all the others students you’ve met here at SCHOOL NAME how would you rank yourself in terms of wealth?” rated on scale from 1 (well below average) to 5 (well above average)</li>
<li>GPA: Self-reported GPA, 0-4point scale</li>
<li>ACT: Self-reported ACT score</li>
<li>Subjective_Well_Being: Average of 5-item satisfaction with life scale by Deiner, rated on scale from 1 (strongly disagree) to 7 (strongly agree). Sample item: “I am satisfied with my life”. See <a href="http://internal.psychology.illinois.edu/~ediener/SWLS.html" class="uri">http://internal.psychology.illinois.edu/~ediener/SWLS.html</a></li>
<li>Positive_Affect: Average of 10-item scale of frequency of experiencing positive emotions over the past week, rated on a scale from 1 (verly slightly to not at all) to 5 (extremely). Sample items: Enthusiastic, Proud, Inspired…Part of the PANAS scale.</li>
<li>Negative_Affect : Average of 10-item scale of frequency of experiencing negative emotions over the past week. Rated on scale from 1( very slightly to not at all) to 5 (extrmely). Sample items: Nervous, irritable, hostile, etc&gt;0. Part of the PANAS scale. See <a href="http://booksite.elsevier.com/9780123745170/Chapter%203/Chapter_3_Worksheet_3.1.pdf" class="uri">http://booksite.elsevier.com/9780123745170/Chapter%203/Chapter_3_Worksheet_3.1.pdf</a></li>
<li>Relationship_Confidence- Average of a 7-item scale of confidence in having romantic relationships, rated on a scale from 1 (not at all characteristic of me) to 5 (very characteristic of me). Sample item: "I am a good partner for a romantic relationship)</li>
<li>Exercise - Exercise score on the Godin Leisure-Time Exercise Quetionnaire. This asks participants to rate how often during a regular week they engage in strenuous, moderate, or light exercise. A total score is calculated as 9<em>strenuous + 5</em>moderate + 3*light. See <a href="http://dapa-toolkit.mrc.ac.uk/documents/en/God/Godin_Leisure-Time_Exercise_Q.pdf" class="uri">http://dapa-toolkit.mrc.ac.uk/documents/en/God/Godin_Leisure-Time_Exercise_Q.pdf</a></li>
<li>Academic_Motivation_Intrinsic - Average score on 6-item measure of intrinsic acadmic motivation. Participants respond to the prompt “Why do you go to college” and respond to each item with a rating from 1 (does not correpond at all) to 7 (corresponds exactly). Sample item: “For the intense feelings I experience when I am communicating my own ideas to others”. See <a href="http://www.er.uqam.ca/nobel/r26710/LRCS/scales/emec_en.doc" class="uri">http://www.er.uqam.ca/nobel/r26710/LRCS/scales/emec_en.doc</a></li>
<li>Academic_Motivation_Extrinsic - Average score on 7-item measure of extinsic acadmic motivation. Participants respond to the prompt “Why do you go to college” and respond to each item with a rating from 1 (does not correpond at all) to 7 (corresponds exactly). Sample item: “Because with only a high-school degree I would not find a high-paying job later one”. See <a href="http://www.er.uqam.ca/nobel/r26710/LRCS/scales/emec_en.doc" class="uri">http://www.er.uqam.ca/nobel/r26710/LRCS/scales/emec_en.doc</a></li>
<li>Academic_Motivation_Amotivation - Average score on 2-item measure of extinsic acadmic motivation. Participants respond to the prompt “Why do you go to college” and respond to each item with a rating from 1 (does not correpond at all) to 7 (corresponds exactly). Sample item: “Honestly, I don’t know; I really feel that I am wasting my time in school.”. See <a href="http://www.er.uqam.ca/nobel/r26710/LRCS/scales/emec_en.doc" class="uri">http://www.er.uqam.ca/nobel/r26710/LRCS/scales/emec_en.doc</a></li>
<li>Inteligence_Value - Measure of degree to which participant values intelligence, rated on a scale from 1 (strongly agree) to 5 (strongly agree). Sample item: “Intelligence greatly contributes to success in life.”. See</li>
<li>Raven_Score - % correct out of 8 items on the Raven Progressive Matrix Scale, a scale of logical thinking/IQ. Adapted from <a href="https://www.raventest.net/" class="uri">https://www.raventest.net/</a>.</li>
</ul>
</div>
</div>
<div id="distribution-of-positive-affect-scores" class="section level3">
<h3><span class="header-section-number">2.1.3</span> Distribution of positive affect scores</h3>
<p>Now we can start to visualize the different distribution as described in 2a-e (pp.68f.)</p>
<div id="visualize-the-distribution" class="section level4">
<h4><span class="header-section-number">2.1.3.1</span> Visualize the distribution</h4>
<blockquote>
<p>Visualize the distribution of positive affect scores (Positive_Affect). Students rate how often they experience each of 10 positive emotions, using a scale from 1 (<em>not at all</em>) to 5 (<em>extremely</em>), then the score is the average of the 10 ratings.</p>
</blockquote>
<p>The reference in the codebook to the PANAS scale is not valid anymore. But I found an explanation and a template with the questionaire on the <a href="https://www.toolshero.com/psychology/personal-happiness/panas-scale/">toolsHero website</a>.</p>
<p>Following the recommendation by the paper <a href="https://s3-eu-west-1.amazonaws.com/s3-euw1-ap-pe-ws4-cws-documents.ri-prod/9781138825529/SoftwareGuide/R_Guide.zip">Getting Started with the New Statistics in R</a> (p.7) I am going to use the <code>ggplot2</code> package. See details to the command at the <a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">ggplot2 web page</a>.</p>
</div>
<div id="histogram" class="section level4">
<h4><span class="header-section-number">2.1.3.2</span> Histogram</h4>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="2-1-end-of-chapter-exercises.html#cb29-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(positive_affect)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 8 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="itns-solutions_files/figure-html/dist-pos-affect-v1-1.png" width="672" /></p>
<p>After executing the above command <code>ggplot2</code> gives us a notification and a warning message:</p>
<p><img src="../img/ggplot2-positive_affect-message-min.png" /></p>
<div id="addressing-the-notification" class="section level5">
<h5><span class="header-section-number">2.1.3.2.1</span> Addressing the notification</h5>
<p>
<div class="alert alert-warning" role="alert">
It is important to experiment with different values of the <code>binwidth</code> parameter to get a feeling about the effects of the visualization of the distribution.
</div>
</p>
<p>I chose a binwidth of .1, meaning that I will get 40 bins as the scale goes from 1-5.</p>
</div>
<div id="addressing-the-warning" class="section level5">
<h5><span class="header-section-number">2.1.3.2.2</span> Addressing the warning</h5>
<p><code>ggplot2</code> warns us that there are data missing in 8 records. Look at the RStudio data browser and scroll down to check it. You will see that at the end of the file, starting with record number 231 some data are missing (“not availabe” = NA). In our next visualization we tell R to remove these missing values silently and to use the binwidth of .1.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="2-1-end-of-chapter-exercises.html#cb32-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(positive_affect)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="fl">0.1</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)  <span class="co"># always experiment with the binwidth</span></span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/dist-pos-affect-v2-1.png" width="672" /></p>
</div>
</div>
<div id="dot-plot" class="section level4">
<h4><span class="header-section-number">2.1.3.3</span> Dot plot</h4>
<p>For more information about this command see: <a href="https://ggplot2.tidyverse.org/reference/geom_dotplot.html" class="uri">https://ggplot2.tidyverse.org/reference/geom_dotplot.html</a></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="2-1-end-of-chapter-exercises.html#cb33-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(positive_affect)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_dotplot</span>(<span class="dt">binwidth =</span> <span class="fl">0.1</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">method =</span> <span class="st">&quot;histodot&quot;</span>, </span>
<span id="cb33-2"><a href="2-1-end-of-chapter-exercises.html#cb33-2"></a><span class="op">+</span><span class="st">     </span><span class="dt">stackratio =</span> <span class="fl">1.1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">coord_fixed</span>(<span class="dt">ratio =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/display-positive-affect-as-dot-plot-1.png" width="672" /></p>
<p>It is a <a href="https://github.com/tidyverse/ggplot2/issues/2203">notorious problem</a> with dot plots produced by <code>ggplot2</code> that the y-axis is normalized and displays meaningless values between 0 and 1. I found recently a workaround <a href="https://stackoverflow.com/questions/49330742/change-y-axis-of-dot-plot-to-reflect-actual-count-using-geom-dotplot">posted at StackOverflow</a>.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="2-1-end-of-chapter-exercises.html#cb34-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="co"># library(ggplot2) ## already loaded with tidyverse</span></span>
<span id="cb34-2"><a href="2-1-end-of-chapter-exercises.html#cb34-2"></a><span class="er">&gt;</span><span class="st"> </span><span class="kw">library</span>(dplyr)  <span class="co">## already loaded with tidyverse</span></span>
<span id="cb34-3"><a href="2-1-end-of-chapter-exercises.html#cb34-3"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">library</span>(ggExtra)</span>
<span id="cb34-4"><a href="2-1-end-of-chapter-exercises.html#cb34-4"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb34-5"><a href="2-1-end-of-chapter-exercises.html#cb34-5"></a><span class="er">&gt;</span><span class="st"> </span>yheight =<span class="st"> </span><span class="dv">20</span>  <span class="co"># taken from the histogramm</span></span>
<span id="cb34-6"><a href="2-1-end-of-chapter-exercises.html#cb34-6"></a><span class="op">&gt;</span><span class="st"> </span><span class="co"># basic dotplot (binwidth = the accuracy of the data)</span></span>
<span id="cb34-7"><a href="2-1-end-of-chapter-exercises.html#cb34-7"></a><span class="er">&gt;</span><span class="st"> </span>dotchart =<span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(<span class="dt">x =</span> positive_affect), <span class="dt">dpi =</span> <span class="dv">600</span>)</span>
<span id="cb34-8"><a href="2-1-end-of-chapter-exercises.html#cb34-8"></a><span class="op">&gt;</span><span class="st"> </span>dotchart =<span class="st"> </span>dotchart <span class="op">+</span><span class="st"> </span><span class="kw">geom_dotplot</span>(<span class="dt">binwidth =</span> <span class="fl">0.1</span>, <span class="dt">method =</span> <span class="st">&quot;histodot&quot;</span>, <span class="dt">dotsize =</span> <span class="dv">1</span>, <span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span>
<span id="cb34-9"><a href="2-1-end-of-chapter-exercises.html#cb34-9"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb34-10"><a href="2-1-end-of-chapter-exercises.html#cb34-10"></a><span class="er">&gt;</span><span class="st"> </span><span class="co"># use coor_fixed(ratio=binwidth*dotsize*max frequency) to setup the right y axis height.</span></span>
<span id="cb34-11"><a href="2-1-end-of-chapter-exercises.html#cb34-11"></a><span class="er">&gt;</span><span class="st"> </span>dotchart =<span class="st"> </span>dotchart <span class="op">+</span><span class="st"> </span><span class="kw">coord_fixed</span>(<span class="dt">ratio =</span> <span class="fl">0.1</span> <span class="op">*</span><span class="st"> </span>yheight)</span>
<span id="cb34-12"><a href="2-1-end-of-chapter-exercises.html#cb34-12"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb34-13"><a href="2-1-end-of-chapter-exercises.html#cb34-13"></a><span class="er">&gt;</span><span class="st"> </span><span class="co"># add tick mark on y axis to reflect frequencies. Note yheight is max frequency.</span></span>
<span id="cb34-14"><a href="2-1-end-of-chapter-exercises.html#cb34-14"></a><span class="er">&gt;</span><span class="st"> </span>dotchart =<span class="st"> </span>dotchart <span class="op">+</span><span class="st"> </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="dt">expand =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>), <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span><span class="op">/</span>yheight), <span class="dt">labels =</span> <span class="kw">seq</span>(<span class="dv">0</span>, </span>
<span id="cb34-15"><a href="2-1-end-of-chapter-exercises.html#cb34-15"></a><span class="op">+</span><span class="st">     </span>yheight))</span>
<span id="cb34-16"><a href="2-1-end-of-chapter-exercises.html#cb34-16"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb34-17"><a href="2-1-end-of-chapter-exercises.html#cb34-17"></a><span class="er">&gt;</span><span class="st"> </span><span class="co"># remove x y lables and remove vertical grid lines</span></span>
<span id="cb34-18"><a href="2-1-end-of-chapter-exercises.html#cb34-18"></a><span class="er">&gt;</span><span class="st"> </span>dotchart =<span class="st"> </span>dotchart <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="ot">NULL</span>, <span class="dt">y =</span> <span class="ot">NULL</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">removeGridX</span>()</span>
<span id="cb34-19"><a href="2-1-end-of-chapter-exercises.html#cb34-19"></a><span class="op">&gt;</span><span class="st"> </span>dotchart</span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
</div>
<div id="interpretation" class="section level4">
<h4><span class="header-section-number">2.1.3.4</span> Interpretation</h4>
<blockquote>
<p>Describe the distribution you see, noting the location, spread, and shape, and the number of major peaks.</p>
</blockquote>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="2-1-end-of-chapter-exercises.html#cb35-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(college_survey1<span class="op">$</span>positive_affect)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   1.200   3.000   3.400   3.433   3.900   5.000       8</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="2-1-end-of-chapter-exercises.html#cb37-1"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">sd</span>(college_survey1<span class="op">$</span>positive_affect, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb37-2"><a href="2-1-end-of-chapter-exercises.html#cb37-2"></a><span class="op">&gt;</span><span class="st"> </span>s</span></code></pre></div>
<pre><code>## [1] 0.71</code></pre>
<blockquote>
<p>Positive affect is relatively normally distributed—there is a single, strong peak and the distribution is fairly symmetrical. The mean score of 3.43 is a little above the midpoint of the 1–5 scale, indicating that students on average feel moderate levels of positive affect. There is wide spread, with <em>s</em> = 0.71 and scores ranging across almost the full range.</p>
</blockquote>
</div>
</div>
<div id="distribution-of-student-age" class="section level3">
<h3><span class="header-section-number">2.1.4</span> Distribution of student age</h3>
<p>The next exercises are similar. I am going to produce just the histograms.</p>
<blockquote>
<p>Visualize and describe the distribution of student age. Note the skew and the high outliers. Note the mean and median and explain why they differ. Would it make sense to delete outliers? Explain.</p>
</blockquote>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="2-1-end-of-chapter-exercises.html#cb39-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(age)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">1</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)  <span class="co"># note the chosen bandwith</span></span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/student-age-description-1.png" width="672" /></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="2-1-end-of-chapter-exercises.html#cb40-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(college_survey1<span class="op">$</span>age)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   18.00   19.00   20.00   21.79   22.00   59.00       4</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="2-1-end-of-chapter-exercises.html#cb42-1"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">sd</span>(college_survey1<span class="op">$</span>age, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb42-2"><a href="2-1-end-of-chapter-exercises.html#cb42-2"></a><span class="op">&gt;</span><span class="st"> </span>s</span></code></pre></div>
<pre><code>## [1] 5.56</code></pre>
<blockquote>
<p>There is strong positive skew, with most students aged 18–22, but a long upper tail of ages ranging up to nearly 60. The mean (21.8 years) is most affected by the outliers, and the median (20 years) is probably a more useful indicator of location. The skew causes the mean to be larger than the median. The college has mostly younger students, but also some older returning and non-traditional students. Removing outliers would misrepresent the sample, by omitting those older students. They should be removed only if there is reason to examine the subgroup of younger students, perhaps aged up to about 32.</p>
</blockquote>
</div>
<div id="distribution-of-exercise-scores" class="section level3">
<h3><span class="header-section-number">2.1.5</span> Distribution of exercise scores</h3>
<p>Again the URL in the code book does not exist anymore but you can <a href="https://hfjc.library.ubc.ca/index.php/HFJC/article/view/82/49">download the article</a> dircetly from Gaston Godin’s web page.</p>
<blockquote>
<p>Visualize the distribution of exercise scores, which are calculated as 9×strenuous + 5×moderate + 3×light, where students report the number of times per week they engage in strenuous, moderate, and light exercise. There is an extreme outlier. What would that extreme value mean? Would it make sense to delete it? Explain. If you do delete it, what happens to the standard deviation? Test your prediction.</p>
</blockquote>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="2-1-end-of-chapter-exercises.html#cb44-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(exercise)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">15</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/exercise-score-description-1.png" width="672" /></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="2-1-end-of-chapter-exercises.html#cb45-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(college_survey1<span class="op">$</span>exercise)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    0.00    2.75   22.00   54.78   61.00 1810.00      23</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="2-1-end-of-chapter-exercises.html#cb47-1"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">sd</span>(college_survey1<span class="op">$</span>exercise, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb47-2"><a href="2-1-end-of-chapter-exercises.html#cb47-2"></a><span class="op">&gt;</span><span class="st"> </span>s</span></code></pre></div>
<pre><code>## [1] 135.28</code></pre>
<blockquote>
<p>There is considerable positive skew. Most students report relatively little exercise, but the right tail pulls the mean (54.7) way above the median (22). The extreme outlier of 1,810 corresponds to engaging in strenuous exercise 201 times per week, which is hardly credible. Most likely, the student didn’t understand the question, made an error, or gave a non-serious answer, so there is good reason to delete this outlier, which would decrease the SD. If it is deleted, <em>s</em> decreases from 135 to 64.7. As always, if you delete an outlier report how, when, and why the descision was made to remove it.</p>
</blockquote>
<p>We can easy find the number of the record (= row) of this outlier when we in the RStudio data browser the column <code>exercise</code> are sorting from high to low.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="2-1-end-of-chapter-exercises.html#cb49-1"></a><span class="op">&gt;</span><span class="st"> </span>outlier &lt;-<span class="st"> </span>college_survey1<span class="op">$</span>exercise[<span class="dv">138</span>]</span>
<span id="cb49-2"><a href="2-1-end-of-chapter-exercises.html#cb49-2"></a><span class="op">&gt;</span><span class="st"> </span>college_survey1<span class="op">$</span>exercise[<span class="dv">138</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb49-3"><a href="2-1-end-of-chapter-exercises.html#cb49-3"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(exercise)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">10</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)  <span class="co"># different bindwidth as before</span></span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/exercise-score-description-without-outlier-1.png" width="672" /></p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="2-1-end-of-chapter-exercises.html#cb50-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(college_survey1<span class="op">$</span>exercise)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    0.00    2.50   20.00   46.77   61.00  385.00      24</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="2-1-end-of-chapter-exercises.html#cb52-1"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">sd</span>(college_survey1<span class="op">$</span>exercise, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb52-2"><a href="2-1-end-of-chapter-exercises.html#cb52-2"></a><span class="op">&gt;</span><span class="st"> </span>college_survey1<span class="op">$</span>exercise[<span class="dv">138</span>] &lt;-<span class="st"> </span>outlier  <span class="co"># restore outlier to get original data frame</span></span>
<span id="cb52-3"><a href="2-1-end-of-chapter-exercises.html#cb52-3"></a><span class="op">&gt;</span><span class="st"> </span>s</span></code></pre></div>
<pre><code>## [1] 64.72</code></pre>
</div>
<div id="distribution-of-raven-scores-and-gpa" class="section level3">
<h3><span class="header-section-number">2.1.6</span> Distribution of Raven scores and GPA</h3>
<blockquote>
<p>Visualize the distribution of Raven scores (Raven_Score), which are the proportion correct on a short 8-item IQ test. Next, visualize the distribution of GPA. Compare the two distributions. Why might they differ in shape?</p>
</blockquote>
<p>By now this should already a routine operation.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="2-1-end-of-chapter-exercises.html#cb54-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(raven_score<span class="op">/</span><span class="dv">100</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="fl">0.05</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/raven-score-distribution-1.png" width="672" /></p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="2-1-end-of-chapter-exercises.html#cb55-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(college_survey1<span class="op">$</span>raven_score<span class="op">/</span><span class="dv">100</span>)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##  0.0000  0.2500  0.3750  0.3771  0.5000  0.8750      26</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="2-1-end-of-chapter-exercises.html#cb57-1"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">sd</span>(college_survey1<span class="op">$</span>raven_score<span class="op">/</span><span class="dv">100</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb57-2"><a href="2-1-end-of-chapter-exercises.html#cb57-2"></a><span class="op">&gt;</span><span class="st"> </span>s</span></code></pre></div>
<pre><code>## [1] 0.2</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="2-1-end-of-chapter-exercises.html#cb59-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(gpa)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="fl">0.1</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/gpa-distribution-1.png" width="672" /></p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="2-1-end-of-chapter-exercises.html#cb60-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(college_survey1<span class="op">$</span>gpa)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   0.800   3.000   3.400   3.343   3.800   4.000       6</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="2-1-end-of-chapter-exercises.html#cb62-1"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">sd</span>(college_survey1<span class="op">$</span>gpa, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb62-2"><a href="2-1-end-of-chapter-exercises.html#cb62-2"></a><span class="op">&gt;</span><span class="st"> </span>s</span></code></pre></div>
<pre><code>## [1] 0.51</code></pre>
<blockquote>
<p>Raven IQ Scores are relatively normally distributed. The mean is .377, median is .375, and standard deviation is .199. In contrast, GPA is very strongly negatively skewed, with scores stacked up near 4.0, the top of the GPA scale. A long tail extends down to very low values of GPA. The mean is 3.34, median is 3.40, and SD is 0.51. Different variables can have different distributions, even for the same sample. However, we expect IQ and GPA to be related, so it’s perhaps surprising that their two distributions are so different. The GPA distribution, with most of the scores concentrated in the 3.5–4.0 range, suggests that the testing is not sufficiently challenging to distinguish among students in the upper parts of the distribution. You may have heard of grade inflation occurring in the last one or two decades. Search online for “college grade inflation”, or similar, and you should easily find statistics describing a dramatic increase in the proportion of A grades in recent years, and interesting discussion about likely causes and consequences.</p>
</blockquote>
</div>
<div id="presentation-of-the-gender-distribution" class="section level3">
<h3><span class="header-section-number">2.1.7</span> Presentation of the gender distribution</h3>
<blockquote>
<p>In this data set (of the original Excel file, pb), Gender is coded as female = 1 and male = 2. ESCI calculates that the mean is <em>M</em> = 1.28 for Gender. Does this make sense? How might you better summarize gender in this sample?</p>
</blockquote>
<blockquote>
<p>No! It doesn’t make sense to calculate a mean for data on a nominal scale. It’s often convenient to represent nominal data with numerical codes, but it’s important to remember that these codes have no numerical meaning, and thus calculation of most descriptive statistics doesn’t make sense. Nominal data can be summarized with frequencies (175 females and 68 males) and relative frequencies (72.0% females and 28.0% males).</p>
</blockquote>
<p>This important difference between numbers and nominal data is in the <code>itns</code> data set already considered and therefore changed. We have two variables <code>Females</code> and <code>Males</code>. These so-called factor variables require a different proceeding:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="2-1-end-of-chapter-exercises.html#cb64-1"></a><span class="op">&gt;</span><span class="st"> </span>n &lt;-<span class="st"> </span><span class="kw">table</span>(college_survey1<span class="op">$</span>gender)</span>
<span id="cb64-2"><a href="2-1-end-of-chapter-exercises.html#cb64-2"></a><span class="op">&gt;</span><span class="st"> </span>res &lt;-<span class="st"> </span><span class="kw">cbind</span>(n, <span class="kw">round</span>(<span class="kw">prop.table</span>(n) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>, <span class="dv">1</span>))</span>
<span id="cb64-3"><a href="2-1-end-of-chapter-exercises.html#cb64-3"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">colnames</span>(res) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Count&quot;</span>, <span class="st">&quot;%&quot;</span>)</span>
<span id="cb64-4"><a href="2-1-end-of-chapter-exercises.html#cb64-4"></a><span class="op">&gt;</span><span class="st"> </span>res</span></code></pre></div>
<pre><code>##        Count  %
## Female   175 72
## Male      68 28</code></pre>
</div>
</div>
<p style="text-align: center;">
<a href="2-picturing-describing-data.html"><button class="btn btn-default">Previous</button></a>
<a href="2-2-put-some-indidual-scores-in-context.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
