<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Picturing &amp; Describing Data | Solutions for ‘Introdcution To The New Statistics’</title>
  <meta name="description" content="This website is a companion book for Introduction to the New Statistics (abbreviated itns). It offers interactive exercises with solutions, and an R tutorial for the end-of-chapter exercises." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Picturing &amp; Describing Data | Solutions for ‘Introdcution To The New Statistics’" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This website is a companion book for Introduction to the New Statistics (abbreviated itns). It offers interactive exercises with solutions, and an R tutorial for the end-of-chapter exercises." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Picturing &amp; Describing Data | Solutions for ‘Introdcution To The New Statistics’" />
  
  <meta name="twitter:description" content="This website is a companion book for Introduction to the New Statistics (abbreviated itns). It offers interactive exercises with solutions, and an R tutorial for the end-of-chapter exercises." />
  

<meta name="author" content="Peter Baumgartner" />


<meta name="date" content="2020-03-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="research-fundamentals.html"/>
<link rel="next" href="end-of-chapter-exercises-1.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/mystyle.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">itns-solutions</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#interactive-exercises"><i class="fa fa-check"></i>Interactive Exercises</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-tutorial"><i class="fa fa-check"></i>R tutorial</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#general-setup"><i class="fa fa-check"></i>General Setup</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#global-options"><i class="fa fa-check"></i>Global Options</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#installing-and-loading-r-packages"><i class="fa fa-check"></i>Installing and loading R packages</a></li>
<li><a href="index.html#theme-adaption-for-the-graphic-display-with-ggplot2">Theme adaption for the graphic display with <code>ggplot2</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="research-questions.html"><a href="research-questions.html"><i class="fa fa-check"></i><b>1</b> Asking and Answering Research Questions</a><ul>
<li class="chapter" data-level="1.1" data-path="research-questions.html"><a href="research-questions.html#interactive-video"><i class="fa fa-check"></i><b>1.1</b> Interactive Video</a><ul>
<li class="chapter" data-level="1.1.1" data-path="research-questions.html"><a href="research-questions.html#chap01-video-research-questions"><i class="fa fa-check"></i><b>1.1.1</b> Research questions</a></li>
<li class="chapter" data-level="1.1.2" data-path="research-questions.html"><a href="research-questions.html#chap01-video-meta-analysis"><i class="fa fa-check"></i><b>1.1.2</b> Meta-analysis</a></li>
<li class="chapter" data-level="1.1.3" data-path="research-questions.html"><a href="research-questions.html#chap01-video-open-science"><i class="fa fa-check"></i><b>1.1.3</b> Open Science</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="research-questions.html"><a href="research-questions.html#glossary"><i class="fa fa-check"></i><b>1.2</b> Glossary</a><ul>
<li class="chapter" data-level="1.2.1" data-path="research-questions.html"><a href="research-questions.html#chap01-glossary-accordion"><i class="fa fa-check"></i><b>1.2.1</b> Accordion</a></li>
<li class="chapter" data-level="1.2.2" data-path="research-questions.html"><a href="research-questions.html#chap01-glossary-drag-words"><i class="fa fa-check"></i><b>1.2.2</b> Drag words</a></li>
<li class="chapter" data-level="1.2.3" data-path="research-questions.html"><a href="research-questions.html#chap01-glossary-memory-game"><i class="fa fa-check"></i><b>1.2.3</b> Memory Game</a></li>
<li class="chapter" data-level="1.2.4" data-path="research-questions.html"><a href="research-questions.html#chap01-glossary-fill-in-the-blanks"><i class="fa fa-check"></i><b>1.2.4</b> Fill in the Blanks</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="research-questions.html"><a href="research-questions.html#research-process"><i class="fa fa-check"></i><b>1.3</b> Research Process</a><ul>
<li class="chapter" data-level="1.3.1" data-path="research-questions.html"><a href="research-questions.html#chap01-research-process-drag-n-drop"><i class="fa fa-check"></i><b>1.3.1</b> Drag &amp; Drop</a></li>
<li class="chapter" data-level="1.3.2" data-path="research-questions.html"><a href="research-questions.html#chap01-sketch-research-form-wizard"><i class="fa fa-check"></i><b>1.3.2</b> Form Wizard</a></li>
<li class="chapter" data-level="1.3.3" data-path="research-questions.html"><a href="research-questions.html#interactive-video-1"><i class="fa fa-check"></i><b>1.3.3</b> Interactive Video</a></li>
<li class="chapter" data-level="1.3.4" data-path="research-questions.html"><a href="research-questions.html#chap01-research-process-phases-summary"><i class="fa fa-check"></i><b>1.3.4</b> Order Phases of the Research Process (Summary)</a></li>
<li class="chapter" data-level="1.3.5" data-path="research-questions.html"><a href="research-questions.html#chap01-estimation-plan-summary"><i class="fa fa-check"></i><b>1.3.5</b> Steps of the Estimation Plan (Summary)</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="research-questions.html"><a href="research-questions.html#meta-analysis"><i class="fa fa-check"></i><b>1.4</b> Meta-Analysis</a><ul>
<li class="chapter" data-level="1.4.1" data-path="research-questions.html"><a href="research-questions.html#chap01-forest-plot-image-hotspots"><i class="fa fa-check"></i><b>1.4.1</b> Explore Forest Plot (Image Hotspots)</a></li>
<li class="chapter" data-level="1.4.2" data-path="research-questions.html"><a href="research-questions.html#chap01-find-point-estimates-find-hotspots"><i class="fa fa-check"></i><b>1.4.2</b> Find Point Estimates in Forest Plot (Find Hotspots)</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="research-questions.html"><a href="research-questions.html#chap01-reporting-accordion"><i class="fa fa-check"></i><b>1.5</b> Reporting (Accordion)</a></li>
<li class="chapter" data-level="1.6" data-path="research-questions.html"><a href="research-questions.html#quizzes-and-assessment"><i class="fa fa-check"></i><b>1.6</b> Quizzes and Assessment</a><ul>
<li class="chapter" data-level="1.6.1" data-path="research-questions.html"><a href="research-questions.html#chap01-quiz-1"><i class="fa fa-check"></i><b>1.6.1</b> Quiz 1</a></li>
<li class="chapter" data-level="1.6.2" data-path="research-questions.html"><a href="research-questions.html#chap01-quiz-2"><i class="fa fa-check"></i><b>1.6.2</b> Quiz 2</a></li>
<li class="chapter" data-level="1.6.3" data-path="research-questions.html"><a href="research-questions.html#chap01-poll-intuitions-true-false"><i class="fa fa-check"></i><b>1.6.3</b> Poll Intuitions (True/False)</a></li>
<li class="chapter" data-level="1.6.4" data-path="research-questions.html"><a href="research-questions.html#chap01-assessment"><i class="fa fa-check"></i><b>1.6.4</b> Assessment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="research-fundamentals.html"><a href="research-fundamentals.html"><i class="fa fa-check"></i><b>2</b> Research Fundamentals: Don’t Fool Yourself</a><ul>
<li class="chapter" data-level="2.1" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-video-research-fundamentals"><i class="fa fa-check"></i><b>2.1</b> Interactive Video</a></li>
<li class="chapter" data-level="2.2" data-path="research-fundamentals.html"><a href="research-fundamentals.html#glossary-1"><i class="fa fa-check"></i><b>2.2</b> Glossary</a><ul>
<li class="chapter" data-level="2.2.1" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-glossary-accordion"><i class="fa fa-check"></i><b>2.2.1</b> Accordion</a></li>
<li class="chapter" data-level="2.2.2" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-glossary-dialog-cards"><i class="fa fa-check"></i><b>2.2.2</b> Dialog Cards</a></li>
<li class="chapter" data-level="2.2.3" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-glossary-drag-words-part1"><i class="fa fa-check"></i><b>2.2.3</b> Drag words Part I</a></li>
<li class="chapter" data-level="2.2.4" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-glossary-drag-words-part2"><i class="fa fa-check"></i><b>2.2.4</b> Drag words Part II</a></li>
<li class="chapter" data-level="2.2.5" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-glossary-flash-cards"><i class="fa fa-check"></i><b>2.2.5</b> Flash Cards</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="research-fundamentals.html"><a href="research-fundamentals.html#fundamental-research-concepts"><i class="fa fa-check"></i><b>2.3</b> Fundamental Research Concepts</a><ul>
<li class="chapter" data-level="2.3.1" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-sample-and-population-find-hotspots"><i class="fa fa-check"></i><b>2.3.1</b> Sample and Population (Find Hotspots)</a></li>
<li class="chapter" data-level="2.3.2" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-DFY-drag-and-drop"><i class="fa fa-check"></i><b>2.3.2</b> DFY: Don’t fool yourself (Drag Words)</a></li>
<li class="chapter" data-level="2.3.3" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-measurement-multiple-choice"><i class="fa fa-check"></i><b>2.3.3</b> Measurement (Multiple Choice)</a></li>
<li class="chapter" data-level="2.3.4" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-important-concepts1-advanced-dropdown"><i class="fa fa-check"></i><b>2.3.4</b> Important Concepts I (Dropdown)</a></li>
<li class="chapter" data-level="2.3.5" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-important-concepts2-advanced-fill-in-the-blanks"><i class="fa fa-check"></i><b>2.3.5</b> Important Concepts II (Fill in the Blanks)</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="research-fundamentals.html"><a href="research-fundamentals.html#quizzes-and-assessment-1"><i class="fa fa-check"></i><b>2.4</b> Quizzes and Assessment</a><ul>
<li class="chapter" data-level="2.4.1" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-quiz-1"><i class="fa fa-check"></i><b>2.4.1</b> Quiz 1</a></li>
<li class="chapter" data-level="2.4.2" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-quiz-2"><i class="fa fa-check"></i><b>2.4.2</b> Quiz 2</a></li>
<li class="chapter" data-level="2.4.3" data-path="research-fundamentals.html"><a href="research-fundamentals.html#chap02-quiz-3"><i class="fa fa-check"></i><b>2.4.3</b> Quiz 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html"><i class="fa fa-check"></i><b>3</b> Picturing &amp; Describing Data</a><ul>
<li class="chapter" data-level="3.1" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#end-of-chapter-exercises"><i class="fa fa-check"></i><b>3.1</b> End-of-Chapter Exercises</a><ul>
<li class="chapter" data-level="3.1.1" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#calculating-decriptive-statistics"><i class="fa fa-check"></i><b>3.1.1</b> Calculating decriptive statistics</a><ul>
<li class="chapter" data-level="3.1.1.1" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#description"><i class="fa fa-check"></i><b>3.1.1.1</b> Description</a></li>
<li class="chapter" data-level="3.1.1.2" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#solution"><i class="fa fa-check"></i><b>3.1.1.2</b> Solution</a></li>
</ul></li>
<li class="chapter" data-level="3.1.2" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#loading-our-first-data-set"><i class="fa fa-check"></i><b>3.1.2</b> Loading our first data set</a><ul>
<li class="chapter" data-level="3.1.2.1" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#inspecting-the-itns-package"><i class="fa fa-check"></i><b>3.1.2.1</b> Inspecting the <code>itns</code>-package</a></li>
<li class="chapter" data-level="3.1.2.2" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#reading-the-codebook-for-college-survey1"><i class="fa fa-check"></i><b>3.1.2.2</b> Reading the codebook for <code>college-survey1</code></a></li>
</ul></li>
<li class="chapter" data-level="3.1.3" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#distribution-of-positive-affect-scores"><i class="fa fa-check"></i><b>3.1.3</b> Distribution of positive affect scores</a><ul>
<li class="chapter" data-level="3.1.3.1" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#visualize-the-distribution"><i class="fa fa-check"></i><b>3.1.3.1</b> Visualize the distribution</a></li>
<li class="chapter" data-level="3.1.3.2" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#histogram"><i class="fa fa-check"></i><b>3.1.3.2</b> Histogram</a><ul>
<li class="chapter" data-level="3.1.3.2.1" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#addressing-the-notification"><i class="fa fa-check"></i><b>3.1.3.2.1</b> Addressing the notification</a></li>
<li class="chapter" data-level="3.1.3.2.2" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#addressing-the-warning"><i class="fa fa-check"></i><b>3.1.3.2.2</b> Addressing the warning</a></li>
</ul></li>
<li class="chapter" data-level="3.1.3.3" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#dot-plot"><i class="fa fa-check"></i><b>3.1.3.3</b> Dot plot</a></li>
<li class="chapter" data-level="3.1.3.4" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#interpretation"><i class="fa fa-check"></i><b>3.1.3.4</b> Interpretation</a></li>
</ul></li>
<li class="chapter" data-level="3.1.4" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#distribution-of-student-age"><i class="fa fa-check"></i><b>3.1.4</b> Distribution of student age</a></li>
<li class="chapter" data-level="3.1.5" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#distribution-of-exercise-scores"><i class="fa fa-check"></i><b>3.1.5</b> Distribution of exercise scores</a></li>
<li class="chapter" data-level="3.1.6" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#distribution-of-raven-scores-and-gpa"><i class="fa fa-check"></i><b>3.1.6</b> Distribution of Raven scores and GPA</a></li>
<li class="chapter" data-level="3.1.7" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#presentation-of-the-gender-distribution"><i class="fa fa-check"></i><b>3.1.7</b> Presentation of the gender distribution</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#put-some-indidual-scores-in-context"><i class="fa fa-check"></i><b>3.2</b> Put some indidual scores in context</a><ul>
<li class="chapter" data-level="3.2.1" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#female-student-on-the-ravens-measure"><i class="fa fa-check"></i><b>3.2.1</b> Female student on the Ravens measure</a></li>
<li class="chapter" data-level="3.2.2" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#the-same-student-in-gpa"><i class="fa fa-check"></i><b>3.2.2</b> The same student in GPA</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#compare-positive-negative-affect-of-a-participant"><i class="fa fa-check"></i><b>3.3</b> Compare positive &amp; negative affect of a participant</a><ul>
<li class="chapter" data-level="3.3.0.1" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#positive-affect"><i class="fa fa-check"></i><b>3.3.0.1</b> Positive Affect</a></li>
<li class="chapter" data-level="3.3.0.2" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#negative-affect"><i class="fa fa-check"></i><b>3.3.0.2</b> Negative Affect</a></li>
<li class="chapter" data-level="3.3.0.3" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#comparison-positive-with-negative-affect"><i class="fa fa-check"></i><b>3.3.0.3</b> Comparison: Positive with Negative Affect</a></li>
<li class="chapter" data-level="3.3.1" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#determine-outliers"><i class="fa fa-check"></i><b>3.3.1</b> Determine outliers</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#religious-beliefs"><i class="fa fa-check"></i><b>3.4</b> Religious Beliefs</a><ul>
<li class="chapter" data-level="3.4.1" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#estimate-the-distribution"><i class="fa fa-check"></i><b>3.4.1</b> Estimate the distribution</a></li>
<li class="chapter" data-level="3.4.2" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#graphic-of-the-religious-data"><i class="fa fa-check"></i><b>3.4.2</b> Graphic of the religious data</a></li>
<li class="chapter" data-level="3.4.3" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#evaluate-the-different-location-parameters"><i class="fa fa-check"></i><b>3.4.3</b> Evaluate the different location parameters</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#working-with-the-oiginal-excel-data-set"><i class="fa fa-check"></i><b>3.5</b> Working with the oiginal Excel data set</a><ul>
<li class="chapter" data-level="3.5.1" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#load-data-set-from-excel-file"><i class="fa fa-check"></i><b>3.5.1</b> Load data set from Excel file</a></li>
<li class="chapter" data-level="3.5.2" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#problems-with-the-exercise-variable"><i class="fa fa-check"></i><b>3.5.2</b> Problems with the Exercise variable</a></li>
<li class="chapter" data-level="3.5.3" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#problems-with-the-ravens_score"><i class="fa fa-check"></i><b>3.5.3</b> Problems with the Ravens_Score</a></li>
<li class="chapter" data-level="3.5.4" data-path="picturing-describing-data.html"><a href="picturing-describing-data.html#gender-data"><i class="fa fa-check"></i><b>3.5.4</b> Gender data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html"><i class="fa fa-check"></i><b>4</b> End-of-Chapter Exercises</a><ul>
<li class="chapter" data-level="4.1" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#personal-remark"><i class="fa fa-check"></i><b>4.1</b> Personal remark</a></li>
<li class="chapter" data-level="4.2" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#find-z-scores"><i class="fa fa-check"></i><b>4.2</b> Find z scores</a></li>
<li class="chapter" data-level="4.3" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#find-percentage-of-better-students"><i class="fa fa-check"></i><b>4.3</b> Find percentage of better students</a></li>
<li class="chapter" data-level="4.4" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#calculation-of-se"><i class="fa fa-check"></i><b>4.4</b> Calculation of SE</a><ul>
<li class="chapter" data-level="4.4.1" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#estimation-1"><i class="fa fa-check"></i><b>4.4.1</b> Estimation 1</a></li>
<li class="chapter" data-level="4.4.2" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#estimation-2"><i class="fa fa-check"></i><b>4.4.2</b> Estimation 2</a></li>
<li class="chapter" data-level="4.4.3" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#calculation"><i class="fa fa-check"></i><b>4.4.3</b> Calculation</a></li>
<li class="chapter" data-level="4.4.4" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#is-the-sample-size-sufficient"><i class="fa fa-check"></i><b>4.4.4</b> Is the sample size sufficient?</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#nursing-home-and-random-sampling"><i class="fa fa-check"></i><b>4.5</b> Nursing home and random sampling</a></li>
<li class="chapter" data-level="4.6" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#skewed-distributions"><i class="fa fa-check"></i><b>4.6</b> Skewed distributions</a></li>
<li class="chapter" data-level="4.7" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#warning-sign-for-skewed-variables"><i class="fa fa-check"></i><b>4.7</b> Warning sign for skewed variables</a></li>
<li class="chapter" data-level="4.8" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#additional-challenge"><i class="fa fa-check"></i><b>4.8</b> Additional challenge:</a></li>
<li class="chapter" data-level="4.9" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#getting-data-from-a-table-on-a-web-page"><i class="fa fa-check"></i><b>4.9</b> Getting data from a table on a web page</a><ul>
<li class="chapter" data-level="4.9.1" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#get-table-data-with-web-scraping"><i class="fa fa-check"></i><b>4.9.1</b> Get table data with web scraping</a></li>
<li class="chapter" data-level="4.9.2" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#copy-table-data-into-a-excel-sheet"><i class="fa fa-check"></i><b>4.9.2</b> Copy table data into a Excel sheet</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#tidy-data"><i class="fa fa-check"></i><b>4.10</b> Tidy data</a><ul>
<li class="chapter" data-level="4.10.1" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#tidy-data-frame-from-web-scraping"><i class="fa fa-check"></i><b>4.10.1</b> Tidy data frame from web scraping</a></li>
<li class="chapter" data-level="4.10.2" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#tidy-data-from-excel-sheet"><i class="fa fa-check"></i><b>4.10.2</b> Tidy data from Excel sheet</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="end-of-chapter-exercises-1.html"><a href="end-of-chapter-exercises-1.html#display-distribution-for-age-at-time-of-death"><i class="fa fa-check"></i><b>4.11</b> Display distribution for age at time of death</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="qr-codes-of-exercises.html"><a href="qr-codes-of-exercises.html"><i class="fa fa-check"></i><b>5</b> QR Codes of Exercises</a><ul>
<li class="chapter" data-level="5.1" data-path="qr-codes-of-exercises.html"><a href="qr-codes-of-exercises.html#chapter-1"><i class="fa fa-check"></i><b>5.1</b> Chapter 1</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/petzi53/itns-solutions" target="blank">GitHub repository</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Solutions for ‘Introdcution To The New Statistics’</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="picturing-describing-data" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Picturing &amp; Describing Data</h1>
<div id="end-of-chapter-exercises" class="section level2">
<h2><span class="header-section-number">3.1</span> End-of-Chapter Exercises</h2>
<div id="calculating-decriptive-statistics" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Calculating decriptive statistics</h3>
<div id="description" class="section level4">
<h4><span class="header-section-number">3.1.1.1</span> Description</h4>
<p>The following table contains a set of ACT scores from a sample of college students. The ACT is a standardized college-readiness exam taken by many U.S. students; scores can range fro 1 to 36.</p>
<table>
<thead>
<tr class="header">
<th>Student</th>
<th>ACT</th>
<th><span class="math inline">\((X~i~ - M)\)</span></th>
<th><span class="math inline">\((X~i~ - M)^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>26</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>2</td>
<td>24</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>3</td>
<td>28</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>4</td>
<td>31</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>5</td>
<td>20</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>6</td>
<td>27</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>7</td>
<td>18</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>8</td>
<td>17</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>9</td>
<td>21</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>10</td>
<td>29</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>11</td>
<td>24</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Total</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha">
<li><strong>Location:</strong> Calculate the mean (<em>M</em>), median, and mode for this sample.</li>
<li><strong>Spread:</strong> Calculate the standard deviation (<em>s</em>), range and interquartile range for this sample. For <em>s</em>, fill in the two columns on the right in the table above, then use the formula to calculate <em>s</em> yourself.</li>
</ol>
</div>
<div id="solution" class="section level4">
<h4><span class="header-section-number">3.1.1.2</span> Solution</h4>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="picturing-describing-data.html#cb21-1"></a><span class="op">&gt;</span><span class="st"> </span>ACT &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">26</span>, <span class="dv">24</span>, <span class="dv">28</span>, <span class="dv">31</span>, <span class="dv">20</span>, <span class="dv">27</span>, <span class="dv">18</span>, <span class="dv">17</span>, <span class="dv">21</span>, <span class="dv">29</span>, <span class="dv">24</span>)</span></code></pre></div>
<p>With <code>summary</code> there is a covenient command in R to print out some of the most important descriptive statistics.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="picturing-describing-data.html#cb22-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(ACT)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   17.00   20.50   24.00   24.09   27.50   31.00</code></pre>
<p>The summary command does not display mode, variance, standard deviation and IQR. With the exception of mode all these command are included in the base R installation. To calculate the mode we need <em>modeest</em>, a package for mode estimation.</p>
<p>In R there are for the same task often several solution possible. I will add some of them.</p>
<table>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Command in R</th>
<th align="right">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean <em>M</em></td>
<td><code>round(mean(ACT),2)</code></td>
<td align="right">24.09</td>
</tr>
<tr class="even">
<td>Median (V1)</td>
<td><code>median(ACT)</code></td>
<td align="right">24</td>
</tr>
<tr class="odd">
<td>Median (V2)</td>
<td><code>fivenum(ACT)[3]</code></td>
<td align="right">24</td>
</tr>
<tr class="even">
<td>quantile (V3)</td>
<td><code>quantile(ACT)[[3]]</code></td>
<td align="right">24</td>
</tr>
<tr class="odd">
<td>Mode</td>
<td><code>mfv(ACT)</code></td>
<td align="right">24</td>
</tr>
<tr class="even">
<td>Variance</td>
<td><code>round(var(ACT),2)</code></td>
<td align="right">21.29</td>
</tr>
<tr class="odd">
<td><em>s</em></td>
<td><code>round(sd(ACT),2)</code></td>
<td align="right">4.61</td>
</tr>
<tr class="even">
<td>Range (V1)</td>
<td><code>range(ACT)</code></td>
<td align="right">17, 31</td>
</tr>
<tr class="odd">
<td>Range (V2)</td>
<td><code>fivenum(ACT)[c(1,5)]</code></td>
<td align="right">17, 31</td>
</tr>
<tr class="even">
<td>IQR</td>
<td><code>IQR(ACT)</code></td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td>Q1,Q3</td>
<td><code>fivenum(ACT)[c(2,4)]</code></td>
<td align="right">20.5, 27.5</td>
</tr>
</tbody>
</table>
<p>To populate the table programmatically I will convert ACT to a data frame <code>ACT_df = as.data.frame(ACT)</code> resp. in a <code>tibble</code> as <a href="https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html">tibbles has some advantages over data frames</a>. (The <code>tibble</code> package is part of the <code>tidyverse</code>.)</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="picturing-describing-data.html#cb24-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="co">### Calling `as_tibble()` on a vector is discouraged, because the behavior is likely to change in the future.  I</span></span>
<span id="cb24-2"><a href="picturing-describing-data.html#cb24-2"></a><span class="er">&gt;</span><span class="st"> </span><span class="co">### am using instead the `enframe` command</span></span>
<span id="cb24-3"><a href="picturing-describing-data.html#cb24-3"></a><span class="er">&gt;</span><span class="st"> </span>ACT_df &lt;-<span class="st"> </span><span class="kw">enframe</span>(ACT, <span class="dt">name =</span> <span class="st">&quot;Student&quot;</span>, <span class="dt">value =</span> <span class="st">&quot;ACT&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="picturing-describing-data.html#cb25-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="co">## using the pipe operator (https://magrittr.tidyverse.org/) using mutate from the dplyr package which is also</span></span>
<span id="cb25-2"><a href="picturing-describing-data.html#cb25-2"></a><span class="er">&gt;</span><span class="st"> </span><span class="co">## included in tidyverse</span></span>
<span id="cb25-3"><a href="picturing-describing-data.html#cb25-3"></a><span class="er">&gt;</span><span class="st"> </span>ACT_df &lt;-<span class="st"> </span>ACT_df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="st">`</span><span class="dt">Xi-M</span><span class="st">`</span> =<span class="st"> </span><span class="kw">round</span>(ACT_df<span class="op">$</span>ACT <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(ACT_df<span class="op">$</span>ACT), <span class="dv">2</span>), <span class="st">`</span><span class="dt">(Xi-M)^2</span><span class="st">`</span> =<span class="st"> </span><span class="kw">round</span>(<span class="st">`</span><span class="dt">Xi-M</span><span class="st">`</span><span class="op">^</span><span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb25-4"><a href="picturing-describing-data.html#cb25-4"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb25-5"><a href="picturing-describing-data.html#cb25-5"></a><span class="er">&gt;</span><span class="st"> </span></span>
<span id="cb25-6"><a href="picturing-describing-data.html#cb25-6"></a><span class="er">&gt;</span><span class="st"> </span>ACT_df &lt;-<span class="st"> </span>ACT_df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">adorn_totals</span>(<span class="st">&quot;row&quot;</span>)  <span class="co"># janitor package to add totals</span></span>
<span id="cb25-7"><a href="picturing-describing-data.html#cb25-7"></a><span class="op">&gt;</span><span class="st"> </span>ACT_df[<span class="dv">12</span>, <span class="dv">3</span>] &lt;-<span class="st"> &quot;   &quot;</span>  <span class="co"># summing up Xi-M does not make sense</span></span>
<span id="cb25-8"><a href="picturing-describing-data.html#cb25-8"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb25-9"><a href="picturing-describing-data.html#cb25-9"></a><span class="er">&gt;</span><span class="st"> </span></span>
<span id="cb25-10"><a href="picturing-describing-data.html#cb25-10"></a><span class="er">&gt;</span><span class="st"> </span>knitr<span class="op">::</span><span class="kw">kable</span>(ACT_df, <span class="dt">booktabs =</span> <span class="ot">TRUE</span>, <span class="dt">caption =</span> <span class="st">&quot;ACT Scores for Exercise 1 of Chapter 3&quot;</span>, <span class="dt">align =</span> <span class="st">&quot;rrrr&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:generate-columns-with-package-dplyr">Table 3.1: </span>ACT Scores for Exercise 1 of Chapter 3</caption>
<thead>
<tr class="header">
<th align="right">Student</th>
<th align="right">ACT</th>
<th align="right">Xi-M</th>
<th align="right">(Xi-M)^2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">26</td>
<td align="right">1.91</td>
<td align="right">3.65</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">24</td>
<td align="right">-0.09</td>
<td align="right">0.01</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">28</td>
<td align="right">3.91</td>
<td align="right">15.29</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">31</td>
<td align="right">6.91</td>
<td align="right">47.75</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">20</td>
<td align="right">-4.09</td>
<td align="right">16.73</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">27</td>
<td align="right">2.91</td>
<td align="right">8.47</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">18</td>
<td align="right">-6.09</td>
<td align="right">37.09</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">17</td>
<td align="right">-7.09</td>
<td align="right">50.27</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">21</td>
<td align="right">-3.09</td>
<td align="right">9.55</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">29</td>
<td align="right">4.91</td>
<td align="right">24.11</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="right">24</td>
<td align="right">-0.09</td>
<td align="right">0.01</td>
</tr>
<tr class="even">
<td align="right">Total</td>
<td align="right">265</td>
<td align="right"></td>
<td align="right">212.93</td>
</tr>
</tbody>
</table>
<p>This table has not the same information as in the book p.505. At first I tried to build it similar but this complicates everything as it is not suitable for using R.</p>
</div>
</div>
<div id="loading-our-first-data-set" class="section level3">
<h3><span class="header-section-number">3.1.2</span> Loading our first data set</h3>
<div id="inspecting-the-itns-package" class="section level4">
<h4><span class="header-section-number">3.1.2.1</span> Inspecting the <code>itns</code>-package</h4>
<p>In the task description of the <em>itns</em>-book you will find the following passage (p.68):</p>
<blockquote>
<p>From the book website, load the <code>College_Survey_1</code> data set. This is a large data set containing data from a wide-ranging survey of college students. You can read the code book for the data file to get a better sense of the different variables measured.</p>
</blockquote>
<p>But you do not need to load the file into R as there are all these data sets already included in the <code>itns</code> package, which we already have loaded into R. In this package the data sets are already cleaned and made compatibel with the R language. This is a great advantage and helps us to concentrate just on the exercises. As in real life you will not have your data already cleaned, I will in the last section of this chapter explain some of the necessary procedures you whould normally apply to every new data set you want to work with.</p>
<p>In the documentation the name of the <code>College_Survey_1</code> data set in the <code>itns</code> pacakge is <code>college_survey1</code>. When you have already the package attached you can find this out with the command <code>ls("package:itns")</code> our better in RStudio with the console command <code>help(package = itns)</code>. (Our you can also go to the “Packages” tab and search for “itns”) The former displays the objects of the package in your RMarkdown file, the latter opens up the documentation page in the RStudio help tab.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="picturing-describing-data.html#cb26-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ls</span>(<span class="st">&quot;package:itns&quot;</span>)  <span class="co"># list all objects of the itns package</span></span></code></pre></div>
<pre><code>##  [1] &quot;altruism_happiness&quot;   &quot;anchor_estimate&quot;      &quot;anchor_estimate_ma&quot;   &quot;body_well&quot;           
##  [5] &quot;campus_involvement&quot;   &quot;clean_moral_johnson&quot;  &quot;clean_moral_schall&quot;   &quot;cohensd_rm&quot;          
##  [9] &quot;college_survey1&quot;      &quot;college_survey2&quot;      &quot;dana&quot;                 &quot;emotion_heartrate&quot;   
## [13] &quot;exam_scores&quot;          &quot;flag_priming_ma&quot;      &quot;home_prices&quot;          &quot;home_prices_holdout&quot; 
## [17] &quot;labels_flavor&quot;        &quot;math_gender_iat&quot;      &quot;math_gender_iat_ma&quot;   &quot;natsal&quot;              
## [21] &quot;organic_moral&quot;        &quot;pen_laptop1&quot;          &quot;pen_laptop2&quot;          &quot;power_performance_ma&quot;
## [25] &quot;rattan&quot;               &quot;religion_sharing&quot;     &quot;religious_belief&quot;     &quot;self_explain_time&quot;   
## [29] &quot;sleep_beauty&quot;         &quot;stickgold&quot;            &quot;study_strategies&quot;     &quot;thomason1&quot;           
## [33] &quot;thomason2&quot;            &quot;thomason3&quot;            &quot;videogame_aggression&quot;</code></pre>
<p>Further on I will only describe the RStudio version. RStudio is the most productive R IDE (Integrated Development Environment) I know about. It is free and works with many platforms. You can download the lastest version at <a href="https://www.rstudio.com/products/rstudio/download/#download" class="uri">https://www.rstudio.com/products/rstudio/download/#download</a></p>
<p>To detect the name of the variables (= columns) and the data structure we use the RStudio <code>View</code> command:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="picturing-describing-data.html#cb28-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="co"># remove first &#39;#&#39; from next line to get code working View(college_survey1) # opens the data set in the RStudio</span></span>
<span id="cb28-2"><a href="picturing-describing-data.html#cb28-2"></a><span class="er">&gt;</span><span class="st"> </span><span class="co"># data browser</span></span></code></pre></div>
</div>
<div id="reading-the-codebook-for-college-survey1" class="section level4">
<h4><span class="header-section-number">3.1.2.2</span> Reading the codebook for <code>college-survey1</code></h4>
<p>Even the data set is already included in the <code>itns</code> package, you still will need to go to the companion website and download the data set as you will need the code book to understand what all the variables and codes mean. To save you time I have it included here.</p>
<p>But keep in mind that the variable names in the <code>college-survey1</code> are slighty different than in <code>College_Survey_1</code>. The main difference is that the R variables are not capitalized. As R is case sensitive, we need always to look up the correct names for the R variables (columns).</p>
<p><strong>Survey of College Attitudes</strong></p>
<p>This is data from survey of college students. The survey was put together as a classroom project, and measures a number of different constructs. Note that not all participants elected to answer all items–blanks represent scales that were not completed by that participant.</p>
<ul>
<li>ID -</li>
<li>Gender : Self-reported gender, Male or Female</li>
<li>Gender_Code: 1 for Female, 2 for Male</li>
<li>Age: Self-reported age in years</li>
<li>School_Year - Self reported, First-year, sophomore, junior, senior, or post-bac</li>
<li>School_Year_Code: 1 = first-year, 2 = sophomore,3 = junior, 4 = senior, 5 = post-bac</li>
<li>Transfer: No if student did not transfer to current school, Yes if student transferred to current school</li>
<li>Transfer_Code: 0 = not a transfer student, 1 = transfer student</li>
<li>Student_Athlete: self-reported, non-athlete, or athlete in or out of season</li>
<li>Student_Athlete_Code: 0 = not a student athlete, 1 = student athlete</li>
<li>Wealth_SR: Single item: “Considering all the others students you’ve met here at SCHOOL NAME how would you rank yourself in terms of wealth?” rated on scale from 1 (well below average) to 5 (well above average)</li>
<li>GPA: Self-reported GPA, 0-4point scale</li>
<li>ACT: Self-reported ACT score</li>
<li>Subjective_Well_Being: Average of 5-item satisfaction with life scale by Deiner, rated on scale from 1 (strongly disagree) to 7 (strongly agree). Sample item: “I am satisfied with my life”. See <a href="http://internal.psychology.illinois.edu/~ediener/SWLS.html" class="uri">http://internal.psychology.illinois.edu/~ediener/SWLS.html</a></li>
<li>Positive_Affect: Average of 10-item scale of frequency of experiencing positive emotions over the past week, rated on a scale from 1 (verly slightly to not at all) to 5 (extremely). Sample items: Enthusiastic, Proud, Inspired…Part of the PANAS scale.</li>
<li>Negative_Affect : Average of 10-item scale of frequency of experiencing negative emotions over the past week. Rated on scale from 1( very slightly to not at all) to 5 (extrmely). Sample items: Nervous, irritable, hostile, etc&gt;0. Part of the PANAS scale. See <a href="http://booksite.elsevier.com/9780123745170/Chapter%203/Chapter_3_Worksheet_3.1.pdf" class="uri">http://booksite.elsevier.com/9780123745170/Chapter%203/Chapter_3_Worksheet_3.1.pdf</a></li>
<li>Relationship_Confidence- Average of a 7-item scale of confidence in having romantic relationships, rated on a scale from 1 (not at all characteristic of me) to 5 (very characteristic of me). Sample item: "I am a good partner for a romantic relationship)</li>
<li>Exercise - Exercise score on the Godin Leisure-Time Exercise Quetionnaire. This asks participants to rate how often during a regular week they engage in strenuous, moderate, or light exercise. A total score is calculated as 9<em>strenuous + 5</em>moderate + 3*light. See <a href="http://dapa-toolkit.mrc.ac.uk/documents/en/God/Godin_Leisure-Time_Exercise_Q.pdf" class="uri">http://dapa-toolkit.mrc.ac.uk/documents/en/God/Godin_Leisure-Time_Exercise_Q.pdf</a></li>
<li>Academic_Motivation_Intrinsic - Average score on 6-item measure of intrinsic acadmic motivation. Participants respond to the prompt “Why do you go to college” and respond to each item with a rating from 1 (does not correpond at all) to 7 (corresponds exactly). Sample item: “For the intense feelings I experience when I am communicating my own ideas to others”. See <a href="http://www.er.uqam.ca/nobel/r26710/LRCS/scales/emec_en.doc" class="uri">http://www.er.uqam.ca/nobel/r26710/LRCS/scales/emec_en.doc</a></li>
<li>Academic_Motivation_Extrinsic - Average score on 7-item measure of extinsic acadmic motivation. Participants respond to the prompt “Why do you go to college” and respond to each item with a rating from 1 (does not correpond at all) to 7 (corresponds exactly). Sample item: “Because with only a high-school degree I would not find a high-paying job later one”. See <a href="http://www.er.uqam.ca/nobel/r26710/LRCS/scales/emec_en.doc" class="uri">http://www.er.uqam.ca/nobel/r26710/LRCS/scales/emec_en.doc</a></li>
<li>Academic_Motivation_Amotivation - Average score on 2-item measure of extinsic acadmic motivation. Participants respond to the prompt “Why do you go to college” and respond to each item with a rating from 1 (does not correpond at all) to 7 (corresponds exactly). Sample item: “Honestly, I don’t know; I really feel that I am wasting my time in school.”. See <a href="http://www.er.uqam.ca/nobel/r26710/LRCS/scales/emec_en.doc" class="uri">http://www.er.uqam.ca/nobel/r26710/LRCS/scales/emec_en.doc</a></li>
<li>Inteligence_Value - Measure of degree to which participant values intelligence, rated on a scale from 1 (strongly agree) to 5 (strongly agree). Sample item: “Intelligence greatly contributes to success in life.”. See</li>
<li>Raven_Score - % correct out of 8 items on the Raven Progressive Matrix Scale, a scale of logical thinking/IQ. Adapted from <a href="https://www.raventest.net/" class="uri">https://www.raventest.net/</a>.</li>
</ul>
</div>
</div>
<div id="distribution-of-positive-affect-scores" class="section level3">
<h3><span class="header-section-number">3.1.3</span> Distribution of positive affect scores</h3>
<p>Now we can start to visualize the different distribution as described in 2a-e (pp.68f.)</p>
<div id="visualize-the-distribution" class="section level4">
<h4><span class="header-section-number">3.1.3.1</span> Visualize the distribution</h4>
<blockquote>
<p>Visualize the distribution of positive affect scores (Positive_Affect). Students rate how often they experience each of 10 positive emotions, using a scale from 1 (<em>not at all</em>) to 5 (<em>extremely</em>), then the score is the average of the 10 ratings.</p>
</blockquote>
<p>The reference in the codebook to the PANAS scale is not valid anymore. But I found an explanation and a template with the questionaire on the <a href="https://www.toolshero.com/psychology/personal-happiness/panas-scale/">toolsHero website</a>.</p>
<p>Following the recommendation by the paper <a href="https://s3-eu-west-1.amazonaws.com/s3-euw1-ap-pe-ws4-cws-documents.ri-prod/9781138825529/SoftwareGuide/R_Guide.zip">Getting Started with the New Statistics in R</a> (p.7) I am going to use the <code>ggplot2</code> package. See details to the command at the <a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">ggplot2 web page</a>.</p>
</div>
<div id="histogram" class="section level4">
<h4><span class="header-section-number">3.1.3.2</span> Histogram</h4>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="picturing-describing-data.html#cb29-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(positive_affect)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 8 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="itns-solutions_files/figure-html/dist-pos-affect-v1-1.png" width="672" /></p>
<p>After executing the above command <code>ggplot2</code> gives us a notification and a warning message:</p>
<p><img src="img/ggplot2-positive_affect-message-min.png" /></p>
<div id="addressing-the-notification" class="section level5">
<h5><span class="header-section-number">3.1.3.2.1</span> Addressing the notification</h5>
<p>
<div class="alert alert-warning" role="alert">
It is important to experiment with different values of the <code>binwidth</code> parameter to get a feeling about the effects of the visualization of the distribution.
</div>
</p>
<p>I chose a binwidth of .1, meaning that I will get 40 bins as the scale goes from 1-5.</p>
</div>
<div id="addressing-the-warning" class="section level5">
<h5><span class="header-section-number">3.1.3.2.2</span> Addressing the warning</h5>
<p><code>ggplot2</code> warns us that there are data missing in 8 records. Look at the RStudio data browser and scroll down to check it. You will see that at the end of the file, starting with record number 231 some data are missing (“not availabe” = NA). In our next visualization we tell R to remove these missing values silently and to use the binwidth of .1.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="picturing-describing-data.html#cb32-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(positive_affect)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="fl">0.1</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)  <span class="co"># always experiment with the binwidth</span></span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/dist-pos-affect-v2-1.png" width="672" /></p>
</div>
</div>
<div id="dot-plot" class="section level4">
<h4><span class="header-section-number">3.1.3.3</span> Dot plot</h4>
<p>For more information about this command see: <a href="https://ggplot2.tidyverse.org/reference/geom_dotplot.html" class="uri">https://ggplot2.tidyverse.org/reference/geom_dotplot.html</a></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="picturing-describing-data.html#cb33-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(positive_affect)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_dotplot</span>(<span class="dt">binwidth =</span> <span class="fl">0.1</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>, <span class="dt">method =</span> <span class="st">&quot;histodot&quot;</span>, </span>
<span id="cb33-2"><a href="picturing-describing-data.html#cb33-2"></a><span class="op">+</span><span class="st">     </span><span class="dt">stackratio =</span> <span class="fl">1.1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">coord_fixed</span>(<span class="dt">ratio =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/display-positive-affect-as-dot-plot-1.png" width="672" /></p>
<p>It is a <a href="https://github.com/tidyverse/ggplot2/issues/2203">notorious problem</a> with dot plots produced by <code>ggplot2</code> that the y-axis is normalized and displays meaningless values between 0 and 1. I found recently a workaround <a href="https://stackoverflow.com/questions/49330742/change-y-axis-of-dot-plot-to-reflect-actual-count-using-geom-dotplot">posted at StackOverflow</a>.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="picturing-describing-data.html#cb34-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="co"># library(ggplot2) ## already loaded with tidyverse</span></span>
<span id="cb34-2"><a href="picturing-describing-data.html#cb34-2"></a><span class="er">&gt;</span><span class="st"> </span><span class="kw">library</span>(dplyr)  <span class="co">## already loaded with tidyverse</span></span>
<span id="cb34-3"><a href="picturing-describing-data.html#cb34-3"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">library</span>(ggExtra)</span>
<span id="cb34-4"><a href="picturing-describing-data.html#cb34-4"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb34-5"><a href="picturing-describing-data.html#cb34-5"></a><span class="er">&gt;</span><span class="st"> </span>yheight =<span class="st"> </span><span class="dv">20</span>  <span class="co"># taken from the histogramm</span></span>
<span id="cb34-6"><a href="picturing-describing-data.html#cb34-6"></a><span class="op">&gt;</span><span class="st"> </span><span class="co"># basic dotplot (binwidth = the accuracy of the data)</span></span>
<span id="cb34-7"><a href="picturing-describing-data.html#cb34-7"></a><span class="er">&gt;</span><span class="st"> </span>dotchart =<span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(<span class="dt">x =</span> positive_affect), <span class="dt">dpi =</span> <span class="dv">600</span>)</span>
<span id="cb34-8"><a href="picturing-describing-data.html#cb34-8"></a><span class="op">&gt;</span><span class="st"> </span>dotchart =<span class="st"> </span>dotchart <span class="op">+</span><span class="st"> </span><span class="kw">geom_dotplot</span>(<span class="dt">binwidth =</span> <span class="fl">0.1</span>, <span class="dt">method =</span> <span class="st">&quot;histodot&quot;</span>, <span class="dt">dotsize =</span> <span class="dv">1</span>, <span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span>
<span id="cb34-9"><a href="picturing-describing-data.html#cb34-9"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb34-10"><a href="picturing-describing-data.html#cb34-10"></a><span class="er">&gt;</span><span class="st"> </span><span class="co"># use coor_fixed(ratio=binwidth*dotsize*max frequency) to setup the right y axis height.</span></span>
<span id="cb34-11"><a href="picturing-describing-data.html#cb34-11"></a><span class="er">&gt;</span><span class="st"> </span>dotchart =<span class="st"> </span>dotchart <span class="op">+</span><span class="st"> </span><span class="kw">coord_fixed</span>(<span class="dt">ratio =</span> <span class="fl">0.1</span> <span class="op">*</span><span class="st"> </span>yheight)</span>
<span id="cb34-12"><a href="picturing-describing-data.html#cb34-12"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb34-13"><a href="picturing-describing-data.html#cb34-13"></a><span class="er">&gt;</span><span class="st"> </span><span class="co"># add tick mark on y axis to reflect frequencies. Note yheight is max frequency.</span></span>
<span id="cb34-14"><a href="picturing-describing-data.html#cb34-14"></a><span class="er">&gt;</span><span class="st"> </span>dotchart =<span class="st"> </span>dotchart <span class="op">+</span><span class="st"> </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="dt">expand =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>), <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span><span class="op">/</span>yheight), <span class="dt">labels =</span> <span class="kw">seq</span>(<span class="dv">0</span>, </span>
<span id="cb34-15"><a href="picturing-describing-data.html#cb34-15"></a><span class="op">+</span><span class="st">     </span>yheight))</span>
<span id="cb34-16"><a href="picturing-describing-data.html#cb34-16"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb34-17"><a href="picturing-describing-data.html#cb34-17"></a><span class="er">&gt;</span><span class="st"> </span><span class="co"># remove x y lables and remove vertical grid lines</span></span>
<span id="cb34-18"><a href="picturing-describing-data.html#cb34-18"></a><span class="er">&gt;</span><span class="st"> </span>dotchart =<span class="st"> </span>dotchart <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="ot">NULL</span>, <span class="dt">y =</span> <span class="ot">NULL</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">removeGridX</span>()</span>
<span id="cb34-19"><a href="picturing-describing-data.html#cb34-19"></a><span class="op">&gt;</span><span class="st"> </span>dotchart</span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
</div>
<div id="interpretation" class="section level4">
<h4><span class="header-section-number">3.1.3.4</span> Interpretation</h4>
<blockquote>
<p>Describe the distribution you see, noting the location, spread, and shape, and the number of major peaks.</p>
</blockquote>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="picturing-describing-data.html#cb35-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(college_survey1<span class="op">$</span>positive_affect)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   1.200   3.000   3.400   3.433   3.900   5.000       8</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="picturing-describing-data.html#cb37-1"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">sd</span>(college_survey1<span class="op">$</span>positive_affect, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb37-2"><a href="picturing-describing-data.html#cb37-2"></a><span class="op">&gt;</span><span class="st"> </span>s</span></code></pre></div>
<pre><code>## [1] 0.71</code></pre>
<blockquote>
<p>Positive affect is relatively normally distributed—there is a single, strong peak and the distribution is fairly symmetrical. The mean score of 3.43 is a little above the midpoint of the 1–5 scale, indicating that students on average feel moderate levels of positive affect. There is wide spread, with <em>s</em> = 0.71 and scores ranging across almost the full range.</p>
</blockquote>
</div>
</div>
<div id="distribution-of-student-age" class="section level3">
<h3><span class="header-section-number">3.1.4</span> Distribution of student age</h3>
<p>The next exercises are similar. I am going to produce just the histograms.</p>
<blockquote>
<p>Visualize and describe the distribution of student age. Note the skew and the high outliers. Note the mean and median and explain why they differ. Would it make sense to delete outliers? Explain.</p>
</blockquote>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="picturing-describing-data.html#cb39-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(age)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">1</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)  <span class="co"># note the chosen bandwith</span></span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/student-age-description-1.png" width="672" /></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="picturing-describing-data.html#cb40-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(college_survey1<span class="op">$</span>age)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   18.00   19.00   20.00   21.79   22.00   59.00       4</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="picturing-describing-data.html#cb42-1"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">sd</span>(college_survey1<span class="op">$</span>age, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb42-2"><a href="picturing-describing-data.html#cb42-2"></a><span class="op">&gt;</span><span class="st"> </span>s</span></code></pre></div>
<pre><code>## [1] 5.56</code></pre>
<blockquote>
<p>There is strong positive skew, with most students aged 18–22, but a long upper tail of ages ranging up to nearly 60. The mean (21.8 years) is most affected by the outliers, and the median (20 years) is probably a more useful indicator of location. The skew causes the mean to be larger than the median. The college has mostly younger students, but also some older returning and non-traditional students. Removing outliers would misrepresent the sample, by omitting those older students. They should be removed only if there is reason to examine the subgroup of younger students, perhaps aged up to about 32.</p>
</blockquote>
</div>
<div id="distribution-of-exercise-scores" class="section level3">
<h3><span class="header-section-number">3.1.5</span> Distribution of exercise scores</h3>
<p>Again the URL in the code book does not exist anymore but you can <a href="https://hfjc.library.ubc.ca/index.php/HFJC/article/view/82/49">download the article</a> dircetly from Gaston Godin’s web page.</p>
<blockquote>
<p>Visualize the distribution of exercise scores, which are calculated as 9×strenuous + 5×moderate + 3×light, where students report the number of times per week they engage in strenuous, moderate, and light exercise. There is an extreme outlier. What would that extreme value mean? Would it make sense to delete it? Explain. If you do delete it, what happens to the standard deviation? Test your prediction.</p>
</blockquote>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="picturing-describing-data.html#cb44-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(exercise)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">15</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/exercise-score-description-1.png" width="672" /></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="picturing-describing-data.html#cb45-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(college_survey1<span class="op">$</span>exercise)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    0.00    2.75   22.00   54.78   61.00 1810.00      23</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="picturing-describing-data.html#cb47-1"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">sd</span>(college_survey1<span class="op">$</span>exercise, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb47-2"><a href="picturing-describing-data.html#cb47-2"></a><span class="op">&gt;</span><span class="st"> </span>s</span></code></pre></div>
<pre><code>## [1] 135.28</code></pre>
<blockquote>
<p>There is considerable positive skew. Most students report relatively little exercise, but the right tail pulls the mean (54.7) way above the median (22). The extreme outlier of 1,810 corresponds to engaging in strenuous exercise 201 times per week, which is hardly credible. Most likely, the student didn’t understand the question, made an error, or gave a non-serious answer, so there is good reason to delete this outlier, which would decrease the SD. If it is deleted, <em>s</em> decreases from 135 to 64.7. As always, if you delete an outlier report how, when, and why the descision was made to remove it.</p>
</blockquote>
<p>We can easy find the number of the record (= row) of this outlier when we in the RStudio data browser the column <code>exercise</code> are sorting from high to low.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="picturing-describing-data.html#cb49-1"></a><span class="op">&gt;</span><span class="st"> </span>outlier &lt;-<span class="st"> </span>college_survey1<span class="op">$</span>exercise[<span class="dv">138</span>]</span>
<span id="cb49-2"><a href="picturing-describing-data.html#cb49-2"></a><span class="op">&gt;</span><span class="st"> </span>college_survey1<span class="op">$</span>exercise[<span class="dv">138</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb49-3"><a href="picturing-describing-data.html#cb49-3"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(exercise)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">10</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)  <span class="co"># different bindwidth as before</span></span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/exercise-score-description-without-outlier-1.png" width="672" /></p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="picturing-describing-data.html#cb50-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(college_survey1<span class="op">$</span>exercise)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##    0.00    2.50   20.00   46.77   61.00  385.00      24</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="picturing-describing-data.html#cb52-1"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">sd</span>(college_survey1<span class="op">$</span>exercise, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb52-2"><a href="picturing-describing-data.html#cb52-2"></a><span class="op">&gt;</span><span class="st"> </span>college_survey1<span class="op">$</span>exercise[<span class="dv">138</span>] &lt;-<span class="st"> </span>outlier  <span class="co"># restore outlier to get original data frame</span></span>
<span id="cb52-3"><a href="picturing-describing-data.html#cb52-3"></a><span class="op">&gt;</span><span class="st"> </span>s</span></code></pre></div>
<pre><code>## [1] 64.72</code></pre>
</div>
<div id="distribution-of-raven-scores-and-gpa" class="section level3">
<h3><span class="header-section-number">3.1.6</span> Distribution of Raven scores and GPA</h3>
<blockquote>
<p>Visualize the distribution of Raven scores (Raven_Score), which are the proportion correct on a short 8-item IQ test. Next, visualize the distribution of GPA. Compare the two distributions. Why might they differ in shape?</p>
</blockquote>
<p>By now this should already a routine operation.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="picturing-describing-data.html#cb54-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(raven_score<span class="op">/</span><span class="dv">100</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="fl">0.05</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/raven-score-distribution-1.png" width="672" /></p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="picturing-describing-data.html#cb55-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(college_survey1<span class="op">$</span>raven_score<span class="op">/</span><span class="dv">100</span>)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##  0.0000  0.2500  0.3750  0.3771  0.5000  0.8750      26</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="picturing-describing-data.html#cb57-1"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">sd</span>(college_survey1<span class="op">$</span>raven_score<span class="op">/</span><span class="dv">100</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb57-2"><a href="picturing-describing-data.html#cb57-2"></a><span class="op">&gt;</span><span class="st"> </span>s</span></code></pre></div>
<pre><code>## [1] 0.2</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="picturing-describing-data.html#cb59-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(college_survey1, <span class="kw">aes</span>(gpa)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="fl">0.1</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/gpa-distribution-1.png" width="672" /></p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="picturing-describing-data.html#cb60-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(college_survey1<span class="op">$</span>gpa)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   0.800   3.000   3.400   3.343   3.800   4.000       6</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="picturing-describing-data.html#cb62-1"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">sd</span>(college_survey1<span class="op">$</span>gpa, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb62-2"><a href="picturing-describing-data.html#cb62-2"></a><span class="op">&gt;</span><span class="st"> </span>s</span></code></pre></div>
<pre><code>## [1] 0.51</code></pre>
<blockquote>
<p>Raven IQ Scores are relatively normally distributed. The mean is .377, median is .375, and standard deviation is .199. In contrast, GPA is very strongly negatively skewed, with scores stacked up near 4.0, the top of the GPA scale. A long tail extends down to very low values of GPA. The mean is 3.34, median is 3.40, and SD is 0.51. Different variables can have different distributions, even for the same sample. However, we expect IQ and GPA to be related, so it’s perhaps surprising that their two distributions are so different. The GPA distribution, with most of the scores concentrated in the 3.5–4.0 range, suggests that the testing is not sufficiently challenging to distinguish among students in the upper parts of the distribution. You may have heard of grade inflation occurring in the last one or two decades. Search online for “college grade inflation”, or similar, and you should easily find statistics describing a dramatic increase in the proportion of A grades in recent years, and interesting discussion about likely causes and consequences.</p>
</blockquote>
</div>
<div id="presentation-of-the-gender-distribution" class="section level3">
<h3><span class="header-section-number">3.1.7</span> Presentation of the gender distribution</h3>
<blockquote>
<p>In this data set (of the original Excel file, pb), Gender is coded as female = 1 and male = 2. ESCI calculates that the mean is <em>M</em> = 1.28 for Gender. Does this make sense? How might you better summarize gender in this sample?</p>
</blockquote>
<blockquote>
<p>No! It doesn’t make sense to calculate a mean for data on a nominal scale. It’s often convenient to represent nominal data with numerical codes, but it’s important to remember that these codes have no numerical meaning, and thus calculation of most descriptive statistics doesn’t make sense. Nominal data can be summarized with frequencies (175 females and 68 males) and relative frequencies (72.0% females and 28.0% males).</p>
</blockquote>
<p>This important difference between numbers and nominal data is in the <code>itns</code> data set already considered and therefore changed. We have two variables <code>Females</code> and <code>Males</code>. These so-called factor variables require a different proceeding:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="picturing-describing-data.html#cb64-1"></a><span class="op">&gt;</span><span class="st"> </span>n &lt;-<span class="st"> </span><span class="kw">table</span>(college_survey1<span class="op">$</span>gender)</span>
<span id="cb64-2"><a href="picturing-describing-data.html#cb64-2"></a><span class="op">&gt;</span><span class="st"> </span>res &lt;-<span class="st"> </span><span class="kw">cbind</span>(n, <span class="kw">round</span>(<span class="kw">prop.table</span>(n) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>, <span class="dv">1</span>))</span>
<span id="cb64-3"><a href="picturing-describing-data.html#cb64-3"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">colnames</span>(res) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Count&quot;</span>, <span class="st">&quot;%&quot;</span>)</span>
<span id="cb64-4"><a href="picturing-describing-data.html#cb64-4"></a><span class="op">&gt;</span><span class="st"> </span>res</span></code></pre></div>
<pre><code>##        Count  %
## Female   175 72
## Male      68 28</code></pre>
</div>
</div>
<div id="put-some-indidual-scores-in-context" class="section level2">
<h2><span class="header-section-number">3.2</span> Put some indidual scores in context</h2>
<div id="female-student-on-the-ravens-measure" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Female student on the Ravens measure</h3>
<blockquote>
<p>One female participant achieved a score of .875 on the Raven measure. What is her z score?</p>
</blockquote>
<p>We can calculate the <em>z</em> score manually with the formula <code>(x - mean(x)) / sd(x)</code> or use the command <code>scale()</code></p>
<div class="alert alert-info" role="alert">
The parenthesis in <code>(x-mean(x)) / sd(x)</code> is important because the precedence of the operators in <code>x-mean(x) / sd(x)</code> would be wrong. We also have to remove the NA values.
</div>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="picturing-describing-data.html#cb66-1"></a><span class="op">&gt;</span><span class="st"> </span>M &lt;-<span class="st"> </span><span class="kw">mean</span>(college_survey1<span class="op">$</span>raven_score, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)<span class="op">/</span><span class="dv">100</span></span>
<span id="cb66-2"><a href="picturing-describing-data.html#cb66-2"></a><span class="op">&gt;</span><span class="st"> </span>s &lt;-<span class="st"> </span><span class="kw">sd</span>(<span class="kw">na.omit</span>(college_survey1<span class="op">$</span>raven_score))<span class="op">/</span><span class="dv">100</span></span>
<span id="cb66-3"><a href="picturing-describing-data.html#cb66-3"></a><span class="op">&gt;</span><span class="st"> </span>(<span class="fl">0.875</span> <span class="op">-</span><span class="st"> </span>M)<span class="op">/</span>s</span></code></pre></div>
<pre><code>## [1] 2.499761</code></pre>
<blockquote>
<p>With <em>X</em> = .875, <em>M</em> = .377, <em>s</em> = .199 we calculate <em>z</em> = 2.50. This student is tied for top score in the sample.</p>
</blockquote>
<p>All these commands are using vectors, e.g. the take all values of the column <code>raven_score</code>. In inspecting the data frame we notice that .875 is the first value. So we can also use the command <code>scale()</code>. To prevent to print out the long list of values we write <code>scale()[1]</code></p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="picturing-describing-data.html#cb68-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">scale</span>(college_survey1<span class="op">$</span>raven_score)[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 2.499761</code></pre>
</div>
<div id="the-same-student-in-gpa" class="section level3">
<h3><span class="header-section-number">3.2.2</span> The same student in GPA</h3>
<blockquote>
<p>The same female participant has a GPA of 3.9. What is her <em>z</em> score for GPA? On which
measure (GPA or Raven) is she more unusual?</p>
</blockquote>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="picturing-describing-data.html#cb70-1"></a><span class="op">&gt;</span><span class="st"> </span>college_survey1<span class="op">$</span>gpa[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 3.9</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="picturing-describing-data.html#cb72-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">mean</span>(college_survey1<span class="op">$</span>gpa, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.343038</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="picturing-describing-data.html#cb74-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">sd</span>(<span class="kw">na.omit</span>(college_survey1<span class="op">$</span>gpa))[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.5083248</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="picturing-describing-data.html#cb76-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">scale</span>(college_survey1<span class="op">$</span>gpa)[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 1.095681</code></pre>
<blockquote>
<p>With <em>X</em> = 3.9, <em>M</em> = 3.34, <em>s</em> = 0.508, we calculate <em>z</em> = 1.10. This participant stands out more on the IQ measure (<em>z</em> = 2.50) than on GPA (z = 1.10).</p>
</blockquote>
</div>
</div>
<div id="compare-positive-negative-affect-of-a-participant" class="section level2">
<h2><span class="header-section-number">3.3</span> Compare positive &amp; negative affect of a participant</h2>
<blockquote>
<p>One participant scored a 2 for Positive Affect and a 2 for Negative Affect. Even though
these raw scores are the same, they are very different within the context of the whole study. Express both as <em>z</em> scores and percentiles. Which score is more unusual?</p>
</blockquote>
<p>Sorting either the column <code>positive_affect</code> or <code>negative_affect</code> we see that the particpant of row 154 is the one who scored a 2 for Positive Affect and a 2 for Negative Affect. But we should not use the direct</p>
<div id="positive-affect" class="section level4">
<h4><span class="header-section-number">3.3.0.1</span> Positive Affect</h4>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="picturing-describing-data.html#cb78-1"></a><span class="op">&gt;</span><span class="st"> </span>college_survey1<span class="op">$</span>positive_affect[<span class="dv">154</span>]</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="picturing-describing-data.html#cb80-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">mean</span>(college_survey1<span class="op">$</span>positive_affect, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.433404</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="picturing-describing-data.html#cb82-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">sd</span>(<span class="kw">na.omit</span>(college_survey1<span class="op">$</span>positive_affect))</span></code></pre></div>
<pre><code>## [1] 0.7135492</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="picturing-describing-data.html#cb84-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">scale</span>(college_survey1<span class="op">$</span>positive_affect)[<span class="dv">154</span>]</span></code></pre></div>
<pre><code>## [1] -2.008837</code></pre>
</div>
<div id="negative-affect" class="section level4">
<h4><span class="header-section-number">3.3.0.2</span> Negative Affect</h4>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="picturing-describing-data.html#cb86-1"></a><span class="op">&gt;</span><span class="st"> </span>college_survey1<span class="op">$</span>negative_affect[<span class="dv">154</span>]</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="picturing-describing-data.html#cb88-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">mean</span>(college_survey1<span class="op">$</span>negative_affect, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 2.322043</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="picturing-describing-data.html#cb90-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">sd</span>(<span class="kw">na.omit</span>(college_survey1<span class="op">$</span>negative_affect))</span></code></pre></div>
<pre><code>## [1] 0.7530565</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="picturing-describing-data.html#cb92-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">scale</span>(college_survey1<span class="op">$</span>negative_affect)[<span class="dv">154</span>]</span></code></pre></div>
<pre><code>## [1] -0.4276473</code></pre>
</div>
<div id="comparison-positive-with-negative-affect" class="section level4">
<h4><span class="header-section-number">3.3.0.3</span> Comparison: Positive with Negative Affect</h4>
<blockquote>
<p><strong>For positive affect:</strong> <em>X</em> = 2.0, <em>M</em> = 3.43, <em>s</em> = 0.71 and we calculate <em>z</em> = −2.01.
<strong>For negative affect:</strong> <em>X</em> = 2.0, <em>M</em> = 2.32, <em>s</em> = 0.75 and we calculate <em>z</em> = −0.43.
The positive affect score is more unusual than the negative affect score, within this sample.</p>
</blockquote>
</div>
<div id="determine-outliers" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Determine outliers</h3>
<p>A <em>z</em> score of more than 3 or less than −3 is sometimes considered an outlier. By this
standard, would the participant who is 59 qualify as an outlier for age? Would the
participant who reported an exercise score of 1,810 qualify as an outlier for exercise?</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="picturing-describing-data.html#cb94-1"></a><span class="op">&gt;</span><span class="st"> </span>college_survey1<span class="op">$</span>age[<span class="dv">69</span>]</span></code></pre></div>
<pre><code>## [1] 59</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="picturing-describing-data.html#cb96-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">mean</span>(college_survey1<span class="op">$</span>age, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 21.78661</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="picturing-describing-data.html#cb98-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">sd</span>(<span class="kw">na.omit</span>(college_survey1<span class="op">$</span>age))</span></code></pre></div>
<pre><code>## [1] 5.555721</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="picturing-describing-data.html#cb100-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">scale</span>(college_survey1<span class="op">$</span>age)[<span class="dv">69</span>]</span></code></pre></div>
<pre><code>## [1] 6.69821</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="picturing-describing-data.html#cb102-1"></a><span class="op">&gt;</span><span class="st"> </span>college_survey1<span class="op">$</span>exercise[<span class="dv">138</span>]</span></code></pre></div>
<pre><code>## [1] 1810</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="picturing-describing-data.html#cb104-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">mean</span>(college_survey1<span class="op">$</span>exercise, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 54.78182</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="picturing-describing-data.html#cb106-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">sd</span>(<span class="kw">na.omit</span>(college_survey1<span class="op">$</span>exercise))</span></code></pre></div>
<pre><code>## [1] 135.2829</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="picturing-describing-data.html#cb108-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">scale</span>(college_survey1<span class="op">$</span>exercise)[<span class="dv">138</span>]</span></code></pre></div>
<pre><code>## [1] 12.97443</code></pre>
<blockquote>
<p>For age, <em>X</em> = 59, <em>M</em> = 21.8, <em>s</em> = 5.56 and we calculate <em>z</em> = 6.69, which is an extreme outlier!
For exercise, <em>X</em> = 1,810, <em>M</em> = 54.8, <em>s</em> = 135.3 and we calculate <em>z</em> = 12.97, which is a very extreme outlier!</p>
</blockquote>
</div>
</div>
<div id="religious-beliefs" class="section level2">
<h2><span class="header-section-number">3.4</span> Religious Beliefs</h2>
<blockquote>
<p>Let’s look at some data about religious beliefs. The religious_belief data set on the book website has data from a large online survey in which participants were asked to report, on a scale from 0 to 100, their belief in the existence of God.</p>
</blockquote>
<div id="estimate-the-distribution" class="section level3">
<h3><span class="header-section-number">3.4.1</span> Estimate the distribution</h3>
<blockquote>
<p>First, sketch the distribution you think this variable will have. Consider the relative
frequencies of people you expect to strongly believe in God (high end of the scale), to
strongly not believe in God (low end of the scale), or to be unsure (middle of the scale).</p>
</blockquote>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="picturing-describing-data.html#cb110-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">summary</span>(religious_belief<span class="op">$</span>belief_in_gd)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    2.00   50.00   49.39  100.00  100.00</code></pre>
<p>The lowest 25% percent do not believe in god and the highest 25% do believe completely (100%) in god.</p>
<blockquote>
<p>I predicted an approximately flat distribution, with similar frequencies of strong, moderate, and non-believers.</p>
</blockquote>
</div>
<div id="graphic-of-the-religious-data" class="section level3">
<h3><span class="header-section-number">3.4.2</span> Graphic of the religious data</h3>
<blockquote>
<p>Now make a picture of these data and describe it in words.</p>
</blockquote>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="picturing-describing-data.html#cb112-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">ggplot</span>(religious_belief, <span class="kw">aes</span>(belief_in_gd)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">10</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="itns-solutions_files/figure-html/distribution-religious-belief-1.png" width="672" /></p>
<p>The distribution is clearly bimodal: Most respondents answered 100 (strongly believe in God) or 0 (strongly disbelieve in God), and relatively few participants gave scores between the extremes. My prediction was quite wrong. This is a good illustration of multiple peaks (two in this case) indicating distinct groups of participants.</p>
</div>
<div id="evaluate-the-different-location-parameters" class="section level3">
<h3><span class="header-section-number">3.4.3</span> Evaluate the different location parameters</h3>
<blockquote>
<p>Does the mean do a good job representing this data picture? Does the median? The mode?
Why do all these measures of location seem to fail?</p>
</blockquote>
<blockquote>
<p>With such a strongly bimodal distribution, none of the three measures of location does a
great job of representing the distribution. Both the mean (48.2) [49.39] and median (50) represent an intermediate level of belief that is actually rare; reporting only one mode would be misleading. The best non-graphical strategy would be to describe the distribution in words and report the location of each mode: one at 0 level of belief, the other at 100.</p>
</blockquote>
</div>
</div>
<div id="working-with-the-oiginal-excel-data-set" class="section level2">
<h2><span class="header-section-number">3.5</span> Working with the oiginal Excel data set</h2>
<div id="load-data-set-from-excel-file" class="section level3">
<h3><span class="header-section-number">3.5.1</span> Load data set from Excel file</h3>
<p>In RStudio there are several options to import data files via the menu available. I generally prefer .csv files using the option <code>From Text (readr)</code>. <code>readr</code> is a package included in <code>tidyverse</code>.</p>
<p><img src="../img/import-dataset-menu-min.png" /></p>
<p>
<img src="../img/import-dataset-window-min.png" />
</p>
<p>In the import data window you can preview the first 50 data. The R program code is displayed in the bottom right section of the window, so that you can automate this step. This is not only time saving but also necessary for better reproducibility. As we already have loaded <code>readr</code> and do not want to display the dataset in RStudio automatically we only need the second line of the program code.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="picturing-describing-data.html#cb113-1"></a><span class="op">&gt;</span><span class="st"> </span>college1 &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;_Material/AllEOC_Exercises/College_Survey_1/College_Survey_1.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double(),
##   Gender = col_character(),
##   Shool_Year = col_character(),
##   Transfer = col_character(),
##   Student_Athlete = col_character(),
##   Exercise = col_character(),
##   Raven_Score = col_character()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<p>After loading the dataset you will see in the console window the parameters <code>readr</code> has used to parse the column specification. This all is done normally correctly, automatically, and hassle-free.</p>
<p>But it is import to check these parsing decisions made by <code>readr</code>. Ignore the strange <code>[31m</code> and <code>[39m</code> strings in the printed output. These are the internal characters for changing text to red color. This is the way <code>readr</code> warns you that there are character columns in the table. You can convert them to factor variable but this is with extra columns for Gender (Gender_Code), Schoolyear (Schoolyear_Code), and Student_Athlete (Student_Athlete_Code) already done.</p>
<p>Remains Exercise and Rave_Score. Both columns contain numbers and should display like the default mode in the format col_double() which is the R code for double precision floating point numbers. We have to inspect these two columns more in detail: Use the command <code>View(college1)</code> from the console or display the data set by choosing it form the tab <code>Environment</code> on the right upper window.</p>
<p>The reason for the wrong format is that the variable <code>Exercise</code> contains ‘-’ and <code>Raven_Score</code> has ‘%’-signs added after the numbers. I will deal with this problem later, when we are going to use one of this variables.</p>
<p>During the inspection of the data set I noticed two other minor problems:</p>
<ul>
<li>The last few rows — from row 244 – 247 are emtpy, respectively filled witn NAs (“not available”). We may delete these rows.</li>
<li>There is a typo in the column name <code>Shool_Year</code> which should be <code>School_Year</code>.</li>
</ul>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="picturing-describing-data.html#cb116-1"></a><span class="op">&gt;</span><span class="st"> </span>college1 &lt;-<span class="st"> </span>college1[<span class="dv">1</span><span class="op">:</span><span class="dv">243</span>, ]  <span class="co"># delete empty rows</span></span>
<span id="cb116-2"><a href="picturing-describing-data.html#cb116-2"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">colnames</span>(college1)[<span class="dv">5</span>] &lt;-<span class="st"> &quot;School_Year&quot;</span></span></code></pre></div>
</div>
<div id="problems-with-the-exercise-variable" class="section level3">
<h3><span class="header-section-number">3.5.2</span> Problems with the Exercise variable</h3>
<p>With the Exercise variable we cannot use the above <code>ggplot2</code> commands to display the histogram. Try it out and you will get the following error message:</p>
<div class="alert alert-danger" role="alert">
Error: StatBin requires a continuous x variable: the x variable is discrete. Perhaps you want stat=“count”?
</div>
<p>The reason is a wrong format of the <code>Exercise</code> variable. Instead of numbers there are some dashes in some of the records. But the dash ‘-’ is a character, so the whole column is convert to a character variable.</p>
<p>The meaning of the dash sign is that there was no exercise reported. To distinguish it from NA (= not available) which means the student did not answer the question, no exercise was coded unfortunately with a ‘-’ instead of a 0. For questions of reproducibility it is always a good idea not to change the original data set. Therefore I will create a new variable <code>Exercise_Code</code>, convert all dashes to 0 and format the column <code>as.double()</code>.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="picturing-describing-data.html#cb117-1"></a><span class="op">&gt;</span><span class="st"> </span>college1<span class="op">$</span>Exercise_Code &lt;-<span class="st"> </span>college1<span class="op">$</span>Exercise  <span class="co"># copy column</span></span>
<span id="cb117-2"><a href="picturing-describing-data.html#cb117-2"></a><span class="op">&gt;</span><span class="st"> </span>college1 &lt;-<span class="st"> </span>college1[, <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">18</span>, <span class="dv">24</span>, <span class="dv">19</span><span class="op">:</span><span class="dv">23</span>)]  <span class="co"># reorder Exercise_Code after Exercise</span></span>
<span id="cb117-3"><a href="picturing-describing-data.html#cb117-3"></a><span class="op">&gt;</span><span class="st"> </span>college1<span class="op">$</span>Exercise_Code[college1<span class="op">$</span>Exercise_Code <span class="op">==</span><span class="st"> &quot;-&quot;</span>] &lt;-<span class="st"> </span><span class="dv">0</span>  <span class="co"># set all &#39;-&#39; to 0</span></span>
<span id="cb117-4"><a href="picturing-describing-data.html#cb117-4"></a><span class="op">&gt;</span><span class="st"> </span>college1<span class="op">$</span>Exercise_Code &lt;-<span class="st"> </span><span class="kw">as.double</span>(college1<span class="op">$</span>Exercise_Code)  <span class="co"># convert column from character to double</span></span></code></pre></div>
<pre><code>## Warning: NAs introduced by coercion</code></pre>
<p>The last line spits out the message “NAs introduced by coercion”. This is a kind of error message saying that some number conversion did not succeed. Instead converting number strings to numbers NAs were created. To find this error was a little bit tricky but finally it turned out that the extreme outlier in row 138 with <code>1,810.00</code> was the problem: The comma in this big figure is interpreted as a character.</p>
<p>We could change this unique value but I will provide a <a href="https://stackoverflow.com/questions/1523126/how-to-read-data-when-some-numbers-contain-commas-as-thousand-separator">general solution taken from StackOverflow</a>. We have to delete the “destroyed” column “Exercise_Code” and start again with the conversion process. In the real praxis we would change simply the code junk above and run the whole program again.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="picturing-describing-data.html#cb119-1"></a><span class="op">&gt;</span><span class="st"> </span>college1 &lt;-<span class="st"> </span>college1[, <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">18</span>, <span class="dv">20</span><span class="op">:</span><span class="dv">24</span>)]  <span class="co"># delete column `Exercise_Code`</span></span>
<span id="cb119-2"><a href="picturing-describing-data.html#cb119-2"></a><span class="op">&gt;</span><span class="st"> </span>college1<span class="op">$</span>Exercise_Code &lt;-<span class="st"> </span>college1<span class="op">$</span>Exercise  <span class="co"># create it again</span></span>
<span id="cb119-3"><a href="picturing-describing-data.html#cb119-3"></a><span class="op">&gt;</span><span class="st"> </span>college1 &lt;-<span class="st"> </span>college1[, <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">18</span>, <span class="dv">24</span>, <span class="dv">19</span><span class="op">:</span><span class="dv">23</span>)]  <span class="co"># reorder Exercise_Code after Exercise</span></span>
<span id="cb119-4"><a href="picturing-describing-data.html#cb119-4"></a><span class="op">&gt;</span><span class="st"> </span>college1<span class="op">$</span>Exercise_Code[college1<span class="op">$</span>Exercise_Code <span class="op">==</span><span class="st"> &quot;-&quot;</span>] &lt;-<span class="st"> </span><span class="dv">0</span>  <span class="co"># set all &#39;-&#39; to 0</span></span>
<span id="cb119-5"><a href="picturing-describing-data.html#cb119-5"></a><span class="op">&gt;</span><span class="st"> </span></span>
<span id="cb119-6"><a href="picturing-describing-data.html#cb119-6"></a><span class="er">&gt;</span><span class="st"> </span><span class="co">## and now the new line: deleting commas and converting to double precision floating point numbers</span></span>
<span id="cb119-7"><a href="picturing-describing-data.html#cb119-7"></a><span class="er">&gt;</span><span class="st"> </span>college1<span class="op">$</span>Exercise_Code &lt;-<span class="st"> </span><span class="kw">as.double</span>(<span class="kw">gsub</span>(<span class="st">&quot;,&quot;</span>, <span class="st">&quot;&quot;</span>, college1<span class="op">$</span>Exercise_Code))</span></code></pre></div>
</div>
<div id="problems-with-the-ravens_score" class="section level3">
<h3><span class="header-section-number">3.5.3</span> Problems with the Ravens_Score</h3>
<p>Here we are confronted with a similar problem. The “%” sign is a character. So we have to recode this variable to get rid of the %-sign and to convert the variable to a double precise floating number. This is similar procedure as we have already done with the <code>Exercise</code> variable.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="picturing-describing-data.html#cb120-1"></a><span class="op">&gt;</span><span class="st"> </span>college1<span class="op">$</span>Raven_Score_Code &lt;-<span class="st"> </span>college1<span class="op">$</span>Raven_Score  <span class="co"># copy column</span></span>
<span id="cb120-2"><a href="picturing-describing-data.html#cb120-2"></a><span class="op">&gt;</span><span class="st"> </span>college1<span class="op">$</span>Raven_Score_Code &lt;-<span class="st"> </span><span class="kw">as.double</span>(<span class="kw">gsub</span>(<span class="st">&quot;%&quot;</span>, <span class="st">&quot;&quot;</span>, college1<span class="op">$</span>Raven_Score_Code))</span></code></pre></div>
</div>
<div id="gender-data" class="section level3">
<h3><span class="header-section-number">3.5.4</span> Gender data</h3>
<p>Here I will reproduce the quote from the book</p>
<blockquote>
<p>In this data set (of the original Excel file, pb), Gender is coded as female = 1 and male = 2. ESCI calculates that the mean is <em>M</em> = 1.28 for Gender. Does this make sense? How might you better summarize gender in this sample? (p.69)</p>
</blockquote>
<blockquote>
<p>No! It doesn’t make sense to calculate a mean for data on a nominal scale. It’s often convenient to represent nominal data with numerical codes, but it’s important to remember that these codes have no numerical meaning, and thus calculation of most descriptive statistics doesn’t make sense. Nominal data can be summarized with frequencies (175 females and 68 males) and relative frequencies (72.0% females and 28.0% males). (p.506)</p>
</blockquote>
<p>We can use the same program lines as we did with the <code>college_survey1</code> data frame.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="picturing-describing-data.html#cb121-1"></a><span class="op">&gt;</span><span class="st"> </span>n &lt;-<span class="st"> </span><span class="kw">table</span>(college1<span class="op">$</span>Gender)</span>
<span id="cb121-2"><a href="picturing-describing-data.html#cb121-2"></a><span class="op">&gt;</span><span class="st"> </span>res &lt;-<span class="st"> </span><span class="kw">cbind</span>(n, <span class="kw">round</span>(<span class="kw">prop.table</span>(n) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>, <span class="dv">1</span>))</span>
<span id="cb121-3"><a href="picturing-describing-data.html#cb121-3"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">colnames</span>(res) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Count&quot;</span>, <span class="st">&quot;%&quot;</span>)</span>
<span id="cb121-4"><a href="picturing-describing-data.html#cb121-4"></a><span class="op">&gt;</span><span class="st"> </span>res</span></code></pre></div>
<pre><code>##        Count  %
## Female   175 72
## Male      68 28</code></pre>
<p>We can also convert the variable <code>Gender_Code</code> or even better the variable <code>Gender_Code</code> into a factor variable. This is done with the <code>forcats</code> package which is already loaded as part of the <code>tidyverse</code>.</p>
<p>When you hover with the mouse in the RStudio data browser over the column “Gender_Code” you will see the small message “column 3: numeric with range 1 - 2”. After running the following code try it again und you will see “column 3: factor with two levels”.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="picturing-describing-data.html#cb123-1"></a><span class="op">&gt;</span><span class="st"> </span>college1<span class="op">$</span>Gender_Code &lt;-<span class="st"> </span><span class="kw">as.factor</span>(college1<span class="op">$</span>Gender_Code)</span>
<span id="cb123-2"><a href="picturing-describing-data.html#cb123-2"></a><span class="op">&gt;</span><span class="st"> </span>college1<span class="op">$</span>Gender_Code</span></code></pre></div>
<pre><code>##   [1] 1 2 1 2 1 2 2 1 1 2 1 2 1 1 1 1 1 1 1 2 1 1 2 2 1 1 2 1 1 1 1 1 2 1 1 2 1 1 1 1 2 2 2 2 1 2 1 1 2 1 2 1 1
##  [54] 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 2 1 2 2 2 1 1 1 2 1 2 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
## [107] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 2 1 1 2 2 1 2 1 2 1 1 1 2 1 1 1 2 1 2 2 2 2 1 1 2 1 2 1 1 1 1 1 2 1
## [160] 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 2 1 2 1 2 1 1 2 1 1 1 1 1 1 2 1 1 1 1 1 1 2 1 1 2 2 1 1 1 1 1 1
## [213] 2 2 1 2 1 2 1 1 2 2 1 2 1 1 1 1 1 1 1 2 1 1 1 1 2 1 2 2 2 2 1
## Levels: 1 2</code></pre>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="picturing-describing-data.html#cb125-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="co"># remove first &#39;#&#39; from next line to get code working View(college1) # opens the data set in the RStudio data</span></span>
<span id="cb125-2"><a href="picturing-describing-data.html#cb125-2"></a><span class="er">&gt;</span><span class="st"> </span><span class="co"># browser</span></span></code></pre></div>
<p>We have successfully converted the numeric column into a categorial variable with 2 levels. All calculations with numbers will fail.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="picturing-describing-data.html#cb126-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">mean</span>(college1<span class="op">$</span>Gender_Code)</span></code></pre></div>
<pre><code>## Warning in mean.default(college1$Gender_Code): argument is not numeric or logical: returning NA</code></pre>
<pre><code>## [1] NA</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="research-fundamentals.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="end-of-chapter-exercises-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["itns-solutions.pdf", "itns-solutions.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
